// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarTentativa = `-- name: BuscarTentativa :one
SELECT id FROM pagamento.tentativa_pagamento WHERE id_externo = $1
`

// A chave desconhecida não é erro do sistema: é uma confirmação sobre
// Tentativa que não existe, e `api/` a traduz em 404 sem gravar nada.
func (q *Queries) BuscarTentativa(ctx context.Context, idExterno string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, buscarTentativa, idExterno)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const confirmacoesNaoAplicadas = `-- name: ConfirmacoesNaoAplicadas :many
SELECT c.id, t.pedido_id, c.resultado, (t.numero = m.maior)::boolean AS corrente
FROM pagamento.confirmacao_recebida c
JOIN pagamento.tentativa_pagamento t ON t.id = c.tentativa_id
JOIN (
    SELECT pedido_id, max(numero) AS maior
    FROM pagamento.tentativa_pagamento GROUP BY pedido_id
) m ON m.pedido_id = t.pedido_id
WHERE c.estado = 'PENDENTE'
ORDER BY c.recebida_em
`

type ConfirmacoesNaoAplicadasRow struct {
	ID        pgtype.UUID
	PedidoID  pgtype.UUID
	Resultado string
	Corrente  bool
}

// O que a varredura de `pedido` lê. `corrente` diz se a confirmação pertence à
// Tentativa corrente do Pedido — a que tem o maior número. A que não pertence
// também sai daqui, para virar terminal em vez de ficar PENDENTE para sempre.
func (q *Queries) ConfirmacoesNaoAplicadas(ctx context.Context) ([]ConfirmacoesNaoAplicadasRow, error) {
	rows, err := q.db.Query(ctx, confirmacoesNaoAplicadas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfirmacoesNaoAplicadasRow
	for rows.Next() {
		var i ConfirmacoesNaoAplicadasRow
		if err := rows.Scan(
			&i.ID,
			&i.PedidoID,
			&i.Resultado,
			&i.Corrente,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contarTentativas = `-- name: ContarTentativas :one
SELECT count(*)::integer FROM pagamento.tentativa_pagamento WHERE pedido_id = $1
`

// Quantas Tentativas o Pedido já teve. O teto é de `pagamento`, dono da
// entidade (AD-8): `pedido` recebe as restantes prontas, e não conta sozinho.
func (q *Queries) ContarTentativas(ctx context.Context, pedidoID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, contarTentativas, pedidoID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const criarTentativa = `-- name: CriarTentativa :exec

INSERT INTO pagamento.tentativa_pagamento (pedido_id, total_centavos, id_externo, numero)
VALUES ($1, $2, $3, $4)
`

type CriarTentativaParams struct {
	PedidoID      pgtype.UUID
	TotalCentavos int64
	IDExterno     string
	Numero        int32
}

// As consultas da porta do Provedor de Pagamento. A Tentativa nasce dentro da
// transação de `pedido.Criar`; a confirmação entra pelo webhook, fora dela; e
// a varredura lê as duas listas sem transação aberta.
func (q *Queries) CriarTentativa(ctx context.Context, arg CriarTentativaParams) error {
	_, err := q.db.Exec(ctx, criarTentativa,
		arg.PedidoID,
		arg.TotalCentavos,
		arg.IDExterno,
		arg.Numero,
	)
	return err
}

const gravarConfirmacao = `-- name: GravarConfirmacao :exec
INSERT INTO pagamento.confirmacao_recebida (tentativa_id, chave_idempotencia, resultado, estado)
VALUES ($1, $2, $3, 'PENDENTE')
`

type GravarConfirmacaoParams struct {
	TentativaID       pgtype.UUID
	ChaveIdempotencia string
	Resultado         string
}

// A restrição única sobre chave_idempotencia é quem decide: o 23505 devolvido
// daqui é sinal de "esta confirmação já entrou", e vira no-op no Go.
func (q *Queries) GravarConfirmacao(ctx context.Context, arg GravarConfirmacaoParams) error {
	_, err := q.db.Exec(ctx, gravarConfirmacao, arg.TentativaID, arg.ChaveIdempotencia, arg.Resultado)
	return err
}

const marcarConfirmacao = `-- name: MarcarConfirmacao :exec
UPDATE pagamento.confirmacao_recebida
SET estado = $1
WHERE id = $2 AND estado = 'PENDENTE'
`

type MarcarConfirmacaoParams struct {
	Estado string
	ID     pgtype.UUID
}

// Terminal em compare-and-swap, como o Status do Pedido: só sai de PENDENTE
// quem ainda está lá, e zero linhas é outro tique que chegou primeiro.
func (q *Queries) MarcarConfirmacao(ctx context.Context, arg MarcarConfirmacaoParams) error {
	_, err := q.db.Exec(ctx, marcarConfirmacao, arg.Estado, arg.ID)
	return err
}

const temConfirmacaoPendente = `-- name: TemConfirmacaoPendente :one
SELECT EXISTS (
    SELECT 1
    FROM pagamento.confirmacao_recebida c
    JOIN pagamento.tentativa_pagamento t ON t.id = c.tentativa_id
    WHERE t.pedido_id = $1 AND c.estado = 'PENDENTE'
)::boolean
`

// A porta da FR-34: existe confirmação ainda PENDENTE para este Pedido?
// A expiração a chama com a linha do Pedido já presa, e desiste se houver uma:
// a ordem do tique sozinha não basta — `aplicar` pode ter falhado, o SKIP LOCKED
// pode ter pulado a linha, e a confirmação pode ter chegado entre os dois passos.
// Em todos, o Comprador pagou no prazo e perderia a Reserva de Estoque.
func (q *Queries) TemConfirmacaoPendente(ctx context.Context, pedidoID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, temConfirmacaoPendente, pedidoID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const tentativasSemConfirmacao = `-- name: TentativasSemConfirmacao :many
SELECT t.id_externo, t.total_centavos, t.numero
FROM pagamento.tentativa_pagamento t
WHERE t.criada_em <= $1
  AND t.criada_em > $2
  AND NOT EXISTS (
      SELECT 1 FROM pagamento.confirmacao_recebida c WHERE c.tentativa_id = t.id
  )
ORDER BY t.criada_em
`

type TentativasSemConfirmacaoParams struct {
	Ate   pgtype.Timestamptz
	Desde pgtype.Timestamptz
}

type TentativasSemConfirmacaoRow struct {
	IDExterno     string
	TotalCentavos int64
	Numero        int32
}

// A emissão é derivada, e não marcada (AD-7): Tentativa cujo atraso venceu e
// que não tem linha na inbox. Marcar "já emiti" exigiria escrever depois do
// POST, e a queda entre uma coisa e outra deixaria a Tentativa órfã para
// sempre; derivando, reemitir é o comportamento normal e a chave única
// transforma o reenvio em no-op.
// O `numero` sai junto porque o Simulado decide pelos centavos só na primeira
// Tentativa (§7.1, AD-8): da segunda em diante aprova.
//
// A janela tem os dois lados. O piso `criada_em > @desde` é o prazo da
// expiração (FR-34): passado ele a Tentativa está morta — a varredura já
// encerrou o Pedido —, e emitir sobre ela não teria efeito nenhum. Sem o piso,
// a faixa que nunca confirma seria relida a cada tique para sempre. Continua
// derivada, e não marcada (AD-7): nada é escrito para sair da lista.
func (q *Queries) TentativasSemConfirmacao(ctx context.Context, arg TentativasSemConfirmacaoParams) ([]TentativasSemConfirmacaoRow, error) {
	rows, err := q.db.Query(ctx, tentativasSemConfirmacao, arg.Ate, arg.Desde)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TentativasSemConfirmacaoRow
	for rows.Next() {
		var i TentativasSemConfirmacaoRow
		if err := rows.Scan(&i.IDExterno, &i.TotalCentavos, &i.Numero); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
