// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gerado

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PagamentoConfirmacaoRecebida struct {
	ID                pgtype.UUID
	TentativaID       pgtype.UUID
	ChaveIdempotencia string
	Resultado         string
	Estado            string
	RecebidaEm        pgtype.Timestamptz
}

type PagamentoTentativaPagamento struct {
	ID            pgtype.UUID
	PedidoID      pgtype.UUID
	TotalCentavos int64
	IDExterno     string
	Numero        int32
	CriadaEm      pgtype.Timestamptz
}
