// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adicionarItem = `-- name: AdicionarItem :one
INSERT INTO carrinho.item_carrinho AS item (carrinho_id, produto_id, quantidade, preco_visto_centavos)
VALUES ($1, $2, $3, $4)
ON CONFLICT (carrinho_id, produto_id) DO UPDATE
SET quantidade = item.quantidade + EXCLUDED.quantidade,
    preco_visto_centavos = EXCLUDED.preco_visto_centavos
WHERE item.quantidade + EXCLUDED.quantidade <= $5::int
RETURNING item.id, item.produto_id, item.quantidade
`

type AdicionarItemParams struct {
	CarrinhoID         pgtype.UUID
	ProdutoID          pgtype.UUID
	Quantidade         int32
	PrecoVistoCentavos int64
	Teto               int32
}

type AdicionarItemRow struct {
	ID         pgtype.UUID
	ProdutoID  pgtype.UUID
	Quantidade int32
}

// A soma e o teto numa ida só: o Produto repetido soma ao Item existente, e a
// soma acima do teto não grava — zero linhas no RETURNING, que carrinho
// traduz em ErrTetoPorItem. O preço visto é sempre o da adição mais recente.
func (q *Queries) AdicionarItem(ctx context.Context, arg AdicionarItemParams) (AdicionarItemRow, error) {
	row := q.db.QueryRow(ctx, adicionarItem,
		arg.CarrinhoID,
		arg.ProdutoID,
		arg.Quantidade,
		arg.PrecoVistoCentavos,
		arg.Teto,
	)
	var i AdicionarItemRow
	err := row.Scan(&i.ID, &i.ProdutoID, &i.Quantidade)
	return i, err
}

const garantirCarrinho = `-- name: GarantirCarrinho :one
INSERT INTO carrinho.carrinho (comprador_id)
VALUES ($1)
ON CONFLICT (comprador_id) DO UPDATE SET comprador_id = EXCLUDED.comprador_id
RETURNING id
`

// O Carrinho nasce na primeira adição. O DO UPDATE que não muda nada existe
// só para o RETURNING devolver o id também quando a linha já existia.
func (q *Queries) GarantirCarrinho(ctx context.Context, compradorID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, garantirCarrinho, compradorID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const removerItem = `-- name: RemoverItem :execrows
DELETE FROM carrinho.item_carrinho AS item
USING carrinho.carrinho AS c
WHERE item.id = $1 AND item.carrinho_id = c.id AND c.comprador_id = $2
`

type RemoverItemParams struct {
	ID          pgtype.UUID
	CompradorID pgtype.UUID
}

// A posse entra no WHERE (AD-11): Item alheio e inexistente afetam as mesmas
// zero linhas.
func (q *Queries) RemoverItem(ctx context.Context, arg RemoverItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removerItem, arg.ID, arg.CompradorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
