// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adicionarItem = `-- name: AdicionarItem :one
INSERT INTO carrinho.item_carrinho AS item (carrinho_id, produto_id, quantidade, preco_visto_centavos)
VALUES ($1, $2, $3, $4)
ON CONFLICT (carrinho_id, produto_id) DO UPDATE
SET quantidade = item.quantidade + EXCLUDED.quantidade,
    preco_visto_centavos = EXCLUDED.preco_visto_centavos
WHERE item.quantidade + EXCLUDED.quantidade <= $5::int
RETURNING item.id, item.produto_id, item.quantidade
`

type AdicionarItemParams struct {
	CarrinhoID         pgtype.UUID
	ProdutoID          pgtype.UUID
	Quantidade         int32
	PrecoVistoCentavos int64
	Teto               int32
}

type AdicionarItemRow struct {
	ID         pgtype.UUID
	ProdutoID  pgtype.UUID
	Quantidade int32
}

// A soma e o teto numa ida só: o Produto repetido soma ao Item existente, e a
// soma acima do teto não grava — zero linhas no RETURNING, que carrinho
// traduz em ErrTetoPorItem. O preço visto é sempre o da adição mais recente.
func (q *Queries) AdicionarItem(ctx context.Context, arg AdicionarItemParams) (AdicionarItemRow, error) {
	row := q.db.QueryRow(ctx, adicionarItem,
		arg.CarrinhoID,
		arg.ProdutoID,
		arg.Quantidade,
		arg.PrecoVistoCentavos,
		arg.Teto,
	)
	var i AdicionarItemRow
	err := row.Scan(&i.ID, &i.ProdutoID, &i.Quantidade)
	return i, err
}

const alterarItem = `-- name: AlterarItem :one
UPDATE carrinho.item_carrinho AS item
SET quantidade = $1, preco_visto_centavos = $2
FROM carrinho.carrinho AS c
WHERE item.id = $3 AND item.carrinho_id = c.id AND c.comprador_id = $4
RETURNING item.id, item.produto_id, item.quantidade
`

type AlterarItemParams struct {
	Quantidade         int32
	PrecoVistoCentavos int64
	ID                 pgtype.UUID
	CompradorID        pgtype.UUID
}

type AlterarItemRow struct {
	ID         pgtype.UUID
	ProdutoID  pgtype.UUID
	Quantidade int32
}

// A quantidade é absoluta, e o preço visto é o da alteração (AD-2). A posse
// volta ao WHERE: BuscarItem já a conferiu, mas a linha pode ter mudado de mãos
// — ou sumido — entre as duas idas.
func (q *Queries) AlterarItem(ctx context.Context, arg AlterarItemParams) (AlterarItemRow, error) {
	row := q.db.QueryRow(ctx, alterarItem,
		arg.Quantidade,
		arg.PrecoVistoCentavos,
		arg.ID,
		arg.CompradorID,
	)
	var i AlterarItemRow
	err := row.Scan(&i.ID, &i.ProdutoID, &i.Quantidade)
	return i, err
}

const buscarItem = `-- name: BuscarItem :one
SELECT item.produto_id, item.quantidade
FROM carrinho.item_carrinho AS item
JOIN carrinho.carrinho AS c ON c.id = item.carrinho_id
WHERE item.id = $1 AND c.comprador_id = $2
`

type BuscarItemParams struct {
	ID          pgtype.UUID
	CompradorID pgtype.UUID
}

type BuscarItemRow struct {
	ProdutoID  pgtype.UUID
	Quantidade int32
}

// O Item do dono, para saber de que Produto ele é. Alheio e inexistente
// voltam as mesmas zero linhas (AD-11).
func (q *Queries) BuscarItem(ctx context.Context, arg BuscarItemParams) (BuscarItemRow, error) {
	row := q.db.QueryRow(ctx, buscarItem, arg.ID, arg.CompradorID)
	var i BuscarItemRow
	err := row.Scan(&i.ProdutoID, &i.Quantidade)
	return i, err
}

const confirmarPrecoVisto = `-- name: ConfirmarPrecoVisto :execrows
UPDATE carrinho.item_carrinho AS item
SET preco_visto_centavos = visto.preco
FROM (
    SELECT i.id, p.preco
    FROM unnest($2::uuid[]) WITH ORDINALITY AS i(id, n)
    JOIN unnest($3::bigint[]) WITH ORDINALITY AS p(preco, n) USING (n)
) AS visto,
     carrinho.carrinho AS c
WHERE item.id = visto.id AND item.carrinho_id = c.id AND c.comprador_id = $1
`

type ConfirmarPrecoVistoParams struct {
	CompradorID pgtype.UUID
	Ids         []pgtype.UUID
	Precos      []int64
}

// A ciência de uma mudança de preço que o Comprador NÃO provocou (AD-17): a
// única escrita de `preco_visto_centavos` fora de Adicionar e Alterar. Quem a
// chama é `pedido`, na transação de entrada no checkout, e sempre com os
// preços que a resposta acabou de reportar — nunca com uma releitura.
//
// Os dois vetores andam em par pela ordinalidade, e a posse entra no WHERE
// (AD-11): Item alheio e inexistente afetam as mesmas zero linhas. Vetor vazio
// é zero linhas e nenhum erro. O :execrows existe para ser conferido: o Go
// compara o número de linhas com o número de vistos, e a escrita parcial é
// erro, nunca silêncio.
//
// A ordem em que as linhas são bloqueadas é do plano do executor, e não do
// vetor: a ordenação por id que o Go faz antes de chamar é determinismo do
// comando, e não a garantia do AD-5 — essa vem de SELECT ... ORDER BY id FOR
// UPDATE, que é de quem decide Estoque, e não desta confirmação.
//
// O `unnest(a, b)` de dois argumentos seria mais curto, mas o analisador do
// sqlc v1.31.1 não o conhece ("function unnest(unknown, unknown) does not
// exist"): o par sai de dois `unnest ... WITH ORDINALITY` juntados pela
// posição, que é a mesma coisa e passa pelo gerador.
func (q *Queries) ConfirmarPrecoVisto(ctx context.Context, arg ConfirmarPrecoVistoParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmarPrecoVisto, arg.CompradorID, arg.Ids, arg.Precos)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const garantirCarrinho = `-- name: GarantirCarrinho :one
INSERT INTO carrinho.carrinho (comprador_id)
VALUES ($1)
ON CONFLICT (comprador_id) DO UPDATE SET comprador_id = EXCLUDED.comprador_id
RETURNING id
`

// O Carrinho nasce na primeira adição. O DO UPDATE que não muda nada existe
// só para o RETURNING devolver o id também quando a linha já existia.
func (q *Queries) GarantirCarrinho(ctx context.Context, compradorID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, garantirCarrinho, compradorID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const limparItens = `-- name: LimparItens :exec
DELETE FROM carrinho.item_carrinho AS item
USING carrinho.carrinho AS c
WHERE item.carrinho_id = c.id AND c.comprador_id = $1
`

// O esvaziar do Comprador (FR-18). O Carrinho em si fica: é um por Comprador e
// não expira. Sem Item nenhum, zero linhas e nenhum erro.
func (q *Queries) LimparItens(ctx context.Context, compradorID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, limparItens, compradorID)
	return err
}

const listarItens = `-- name: ListarItens :many
SELECT item.id, item.produto_id, item.quantidade, item.preco_visto_centavos
FROM carrinho.item_carrinho AS item
JOIN carrinho.carrinho AS c ON c.id = item.carrinho_id
WHERE c.comprador_id = $1
ORDER BY item.id
`

type ListarItensRow struct {
	ID                 pgtype.UUID
	ProdutoID          pgtype.UUID
	Quantidade         int32
	PrecoVistoCentavos int64
}

// Leitura pura (AD-17): não há UPDATE aqui. O preço visto sai da consulta para
// a revalidação dizer "de X para Y" (4.4), mas quem o grava não é esta.
// O id é uuidv7, então a ordem é a da adição.
func (q *Queries) ListarItens(ctx context.Context, compradorID pgtype.UUID) ([]ListarItensRow, error) {
	rows, err := q.db.Query(ctx, listarItens, compradorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarItensRow
	for rows.Next() {
		var i ListarItensRow
		if err := rows.Scan(
			&i.ID,
			&i.ProdutoID,
			&i.Quantidade,
			&i.PrecoVistoCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const quantidadeDoProduto = `-- name: QuantidadeDoProduto :one
SELECT COALESCE(SUM(item.quantidade), 0)::int AS quantidade
FROM carrinho.item_carrinho AS item
JOIN carrinho.carrinho AS c ON c.id = item.carrinho_id
WHERE c.comprador_id = $1 AND item.produto_id = $2
`

type QuantidadeDoProdutoParams struct {
	CompradorID pgtype.UUID
	ProdutoID   pgtype.UUID
}

// Quanto o dono já tem do Produto: a soma que o teto e o Estoque recusam. A
// soma sobre nenhuma linha é o zero do COALESCE, e por isso a consulta não
// cria o Carrinho de quem só tentou adicionar.
func (q *Queries) QuantidadeDoProduto(ctx context.Context, arg QuantidadeDoProdutoParams) (int32, error) {
	row := q.db.QueryRow(ctx, quantidadeDoProduto, arg.CompradorID, arg.ProdutoID)
	var quantidade int32
	err := row.Scan(&quantidade)
	return quantidade, err
}

const removerItem = `-- name: RemoverItem :execrows
DELETE FROM carrinho.item_carrinho AS item
USING carrinho.carrinho AS c
WHERE item.id = $1 AND item.carrinho_id = c.id AND c.comprador_id = $2
`

type RemoverItemParams struct {
	ID          pgtype.UUID
	CompradorID pgtype.UUID
}

// A posse entra no WHERE (AD-11): Item alheio e inexistente afetam as mesmas
// zero linhas.
func (q *Queries) RemoverItem(ctx context.Context, arg RemoverItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removerItem, arg.ID, arg.CompradorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
