// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gerado

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CarrinhoCarrinho struct {
	ID          pgtype.UUID
	CompradorID pgtype.UUID
}

type CarrinhoItemCarrinho struct {
	ID                 pgtype.UUID
	CarrinhoID         pgtype.UUID
	ProdutoID          pgtype.UUID
	Quantidade         int32
	PrecoVistoCentavos int64
}
