// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"
)

const buscarCompradorPorEmail = `-- name: BuscarCompradorPorEmail :one

SELECT id, nome, email, senha_hash
FROM identidade.comprador
WHERE email = $1
`

// Uma consulta por módulo nesta estória: o que a 1.3 precisa provar é que o
// sqlc analisa `DEFAULT uuidv7()` (verificação 2 do passo 0). As consultas de
// verdade chegam com a regra, nas Épicas 2 e 3.
func (q *Queries) BuscarCompradorPorEmail(ctx context.Context, email string) (IdentidadeComprador, error) {
	row := q.db.QueryRow(ctx, buscarCompradorPorEmail, email)
	var i IdentidadeComprador
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
	)
	return i, err
}
