// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarEndereco = `-- name: AtualizarEndereco :one
UPDATE identidade.endereco
SET destinatario = $1,
    cep = $2,
    logradouro = $3,
    numero = $4,
    complemento = $5,
    bairro = $6,
    cidade = $7,
    uf = $8
WHERE id = $9 AND comprador_id = $10
RETURNING id, destinatario, cep, logradouro, numero, complemento, bairro, cidade, uf
`

type AtualizarEnderecoParams struct {
	Destinatario string
	Cep          string
	Logradouro   string
	Numero       string
	Complemento  string
	Bairro       string
	Cidade       string
	Uf           string
	ID           pgtype.UUID
	CompradorID  pgtype.UUID
}

type AtualizarEnderecoRow struct {
	ID           pgtype.UUID
	Destinatario string
	Cep          string
	Logradouro   string
	Numero       string
	Complemento  string
	Bairro       string
	Cidade       string
	Uf           string
}

func (q *Queries) AtualizarEndereco(ctx context.Context, arg AtualizarEnderecoParams) (AtualizarEnderecoRow, error) {
	row := q.db.QueryRow(ctx, atualizarEndereco,
		arg.Destinatario,
		arg.Cep,
		arg.Logradouro,
		arg.Numero,
		arg.Complemento,
		arg.Bairro,
		arg.Cidade,
		arg.Uf,
		arg.ID,
		arg.CompradorID,
	)
	var i AtualizarEnderecoRow
	err := row.Scan(
		&i.ID,
		&i.Destinatario,
		&i.Cep,
		&i.Logradouro,
		&i.Numero,
		&i.Complemento,
		&i.Bairro,
		&i.Cidade,
		&i.Uf,
	)
	return i, err
}

const atualizarSenhaDoComprador = `-- name: AtualizarSenhaDoComprador :one
UPDATE identidade.comprador
SET senha_hash = $2
WHERE id = $1
RETURNING email
`

type AtualizarSenhaDoCompradorParams struct {
	ID        pgtype.UUID
	SenhaHash string
}

// Quem chama já resolveu o token de redefinição no Redis, e é ele que provou
// de quem é a conta — por isso a cláusula é pelo id, e não pelo e-mail.
//
// O RETURNING devolve o e-mail porque o contador de tentativas do bloqueio
// chaveia por ele, e quem redefiniu a senha tem de sair do bloqueio: sem isto
// a consulta seria :exec, e quem chama pagaria um SELECT a mais só para saber
// de quem era o id que ele acabou de escrever. De quebra, o :one distingue o
// UPDATE que não achou linha nenhuma, que o :exec engoliria em silêncio.
func (q *Queries) AtualizarSenhaDoComprador(ctx context.Context, arg AtualizarSenhaDoCompradorParams) (string, error) {
	row := q.db.QueryRow(ctx, atualizarSenhaDoComprador, arg.ID, arg.SenhaHash)
	var email string
	err := row.Scan(&email)
	return email, err
}

const buscarAdministradorPorEmail = `-- name: BuscarAdministradorPorEmail :one
SELECT id, nome, email, senha_hash
FROM identidade.administrador
WHERE email = $1
`

// O molde é o de Comprador, e a tabela é outra de propósito: são duas consultas
// porque são dois papéis, e o papel de quem entra é decidido pela rota que
// chamou — nunca pela ordem em que as tabelas seriam tentadas.
func (q *Queries) BuscarAdministradorPorEmail(ctx context.Context, email string) (IdentidadeAdministrador, error) {
	row := q.db.QueryRow(ctx, buscarAdministradorPorEmail, email)
	var i IdentidadeAdministrador
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
	)
	return i, err
}

const buscarCompradorPorEmail = `-- name: BuscarCompradorPorEmail :one

SELECT id, nome, email, senha_hash
FROM identidade.comprador
WHERE email = $1
`

// Uma consulta por módulo nesta estória: o que a 1.3 precisa provar é que o
// sqlc analisa `DEFAULT uuidv7()` (verificação 2 do passo 0). As consultas de
// verdade chegam com a regra, nas Épicas 2 e 3.
func (q *Queries) BuscarCompradorPorEmail(ctx context.Context, email string) (IdentidadeComprador, error) {
	row := q.db.QueryRow(ctx, buscarCompradorPorEmail, email)
	var i IdentidadeComprador
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Email,
		&i.SenhaHash,
	)
	return i, err
}

const buscarCompradorPorID = `-- name: BuscarCompradorPorID :one
SELECT id, nome, email
FROM identidade.comprador
WHERE id = $1
`

type BuscarCompradorPorIDRow struct {
	ID    pgtype.UUID
	Nome  string
	Email string
}

// O Comprador pelo identificador, e não pelo e-mail: quem chama já tem o
// `comprador_id` de uma linha que o aponta (o Pedido, no painel do
// Administrador da 6.4). Sem `senha_hash`: esta consulta não autentica
// ninguém, e trazer o hash para uma leitura de exibição seria carga a mais
// num caminho que nunca a usa.
func (q *Queries) BuscarCompradorPorID(ctx context.Context, id pgtype.UUID) (BuscarCompradorPorIDRow, error) {
	row := q.db.QueryRow(ctx, buscarCompradorPorID, id)
	var i BuscarCompradorPorIDRow
	err := row.Scan(&i.ID, &i.Nome, &i.Email)
	return i, err
}

const buscarEndereco = `-- name: BuscarEndereco :one
SELECT id, destinatario, cep, logradouro, numero, complemento, bairro, cidade, uf
FROM identidade.endereco
WHERE id = $1 AND comprador_id = $2
`

type BuscarEnderecoParams struct {
	ID          pgtype.UUID
	CompradorID pgtype.UUID
}

type BuscarEnderecoRow struct {
	ID           pgtype.UUID
	Destinatario string
	Cep          string
	Logradouro   string
	Numero       string
	Complemento  string
	Bairro       string
	Cidade       string
	Uf           string
}

// Um Endereço só, do dono: é o que o Frete da 5.3 lê para tirar o CEP, e o
// que a criação do Pedido (5.6) congela. O dono no WHERE, como nas outras.
func (q *Queries) BuscarEndereco(ctx context.Context, arg BuscarEnderecoParams) (BuscarEnderecoRow, error) {
	row := q.db.QueryRow(ctx, buscarEndereco, arg.ID, arg.CompradorID)
	var i BuscarEnderecoRow
	err := row.Scan(
		&i.ID,
		&i.Destinatario,
		&i.Cep,
		&i.Logradouro,
		&i.Numero,
		&i.Complemento,
		&i.Bairro,
		&i.Cidade,
		&i.Uf,
	)
	return i, err
}

const criarComprador = `-- name: CriarComprador :one
INSERT INTO identidade.comprador (nome, email, senha_hash)
VALUES ($1, $2, $3)
RETURNING id, nome
`

type CriarCompradorParams struct {
	Nome      string
	Email     string
	SenhaHash string
}

type CriarCompradorRow struct {
	ID   pgtype.UUID
	Nome string
}

// O e-mail chega já normalizado: quem grava é identidade.Cadastrar, e a coluna
// tem CHECK (email = lower(email)). A duplicidade sai da violação do UNIQUE —
// um SELECT antes do INSERT deixaria dois cadastros simultâneos passarem.
func (q *Queries) CriarComprador(ctx context.Context, arg CriarCompradorParams) (CriarCompradorRow, error) {
	row := q.db.QueryRow(ctx, criarComprador, arg.Nome, arg.Email, arg.SenhaHash)
	var i CriarCompradorRow
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const criarEndereco = `-- name: CriarEndereco :one
INSERT INTO identidade.endereco
    (comprador_id, destinatario, cep, logradouro, numero, complemento, bairro, cidade, uf)
SELECT $1, $2, $3, $4, $5, $6, $7, $8, $9
WHERE (SELECT count(*) FROM identidade.endereco WHERE comprador_id = $1) < $10::bigint
RETURNING id, destinatario, cep, logradouro, numero, complemento, bairro, cidade, uf
`

type CriarEnderecoParams struct {
	CompradorID  pgtype.UUID
	Destinatario string
	Cep          string
	Logradouro   string
	Numero       string
	Complemento  string
	Bairro       string
	Cidade       string
	Uf           string
	Maximo       int64
}

type CriarEnderecoRow struct {
	ID           pgtype.UUID
	Destinatario string
	Cep          string
	Logradouro   string
	Numero       string
	Complemento  string
	Bairro       string
	Cidade       string
	Uf           string
}

// O teto por Comprador entra no PRÓPRIO INSERT, e não num SELECT count antes:
// assim é uma ida ao banco só, e zero linhas devolvidas significa "o teto foi
// alcançado" — o mesmo idioma do compare-and-swap do Pedido.
// O CEP chega com os oito dígitos e a UF em maiúsculas: quem normaliza é
// identidade.CriarEndereco, e as colunas têm os CHECKs.
func (q *Queries) CriarEndereco(ctx context.Context, arg CriarEnderecoParams) (CriarEnderecoRow, error) {
	row := q.db.QueryRow(ctx, criarEndereco,
		arg.CompradorID,
		arg.Destinatario,
		arg.Cep,
		arg.Logradouro,
		arg.Numero,
		arg.Complemento,
		arg.Bairro,
		arg.Cidade,
		arg.Uf,
		arg.Maximo,
	)
	var i CriarEnderecoRow
	err := row.Scan(
		&i.ID,
		&i.Destinatario,
		&i.Cep,
		&i.Logradouro,
		&i.Numero,
		&i.Complemento,
		&i.Bairro,
		&i.Cidade,
		&i.Uf,
	)
	return i, err
}

const listarEnderecos = `-- name: ListarEnderecos :many
SELECT id, destinatario, cep, logradouro, numero, complemento, bairro, cidade, uf
FROM identidade.endereco
WHERE comprador_id = $1
ORDER BY id
`

type ListarEnderecosRow struct {
	ID           pgtype.UUID
	Destinatario string
	Cep          string
	Logradouro   string
	Numero       string
	Complemento  string
	Bairro       string
	Cidade       string
	Uf           string
}

// As quatro do Endereço (2.5). As três que tocam uma linha específica trazem
// `AND comprador_id = @comprador_id` DENTRO da cláusula, e não numa checagem
// depois (AD-11): Endereço de outro dono e Endereço inexistente saem os dois
// como "nenhuma linha", que é o mesmo 404 — não vaza existência.
//
// A ordem é por `id`, e o id é uuidv7: monotônico no tempo, então ordenar por
// ele é ordenar por criação sem carregar uma coluna de instante que nenhuma
// tela exibe.
func (q *Queries) ListarEnderecos(ctx context.Context, compradorID pgtype.UUID) ([]ListarEnderecosRow, error) {
	rows, err := q.db.Query(ctx, listarEnderecos, compradorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarEnderecosRow
	for rows.Next() {
		var i ListarEnderecosRow
		if err := rows.Scan(
			&i.ID,
			&i.Destinatario,
			&i.Cep,
			&i.Logradouro,
			&i.Numero,
			&i.Complemento,
			&i.Bairro,
			&i.Cidade,
			&i.Uf,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerEndereco = `-- name: RemoverEndereco :execrows
DELETE FROM identidade.endereco
WHERE id = $1 AND comprador_id = $2
`

type RemoverEnderecoParams struct {
	ID          pgtype.UUID
	CompradorID pgtype.UUID
}

// :execrows, e não :exec: zero linhas é a resposta de "não é seu ou não
// existe", e o :exec a engoliria em silêncio devolvendo 204 para o DELETE de
// Endereço alheio.
// Nenhum Pedido é tocado — o Pedido congela o Endereço na criação (AD-3).
func (q *Queries) RemoverEndereco(ctx context.Context, arg RemoverEnderecoParams) (int64, error) {
	result, err := q.db.Exec(ctx, removerEndereco, arg.ID, arg.CompradorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
