// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gerado

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentidadeAdministrador struct {
	ID        pgtype.UUID
	Nome      string
	Email     string
	SenhaHash string
}

type IdentidadeComprador struct {
	ID        pgtype.UUID
	Nome      string
	Email     string
	SenhaHash string
}
