// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buscarProdutoPorID = `-- name: BuscarProdutoPorID :one

SELECT id, nome, descricao, preco_centavos, imagem_url, vendedor_id, categoria_id
FROM catalogo.produto
WHERE id = $1
`

// Uma consulta por módulo nesta estória: o que a 1.3 precisa provar é que o
// sqlc analisa `DEFAULT uuidv7()` (verificação 2 do passo 0). As consultas de
// verdade chegam com a regra, nas Épicas 2 e 3.
func (q *Queries) BuscarProdutoPorID(ctx context.Context, id pgtype.UUID) (CatalogoProduto, error) {
	row := q.db.QueryRow(ctx, buscarProdutoPorID, id)
	var i CatalogoProduto
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.PrecoCentavos,
		&i.ImagemUrl,
		&i.VendedorID,
		&i.CategoriaID,
	)
	return i, err
}
