// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarCategoria = `-- name: AtualizarCategoria :one
UPDATE catalogo.categoria SET nome = $1
WHERE id = $2
RETURNING id, nome
`

type AtualizarCategoriaParams struct {
	Nome string
	ID   pgtype.UUID
}

type AtualizarCategoriaRow struct {
	ID   pgtype.UUID
	Nome string
}

func (q *Queries) AtualizarCategoria(ctx context.Context, arg AtualizarCategoriaParams) (AtualizarCategoriaRow, error) {
	row := q.db.QueryRow(ctx, atualizarCategoria, arg.Nome, arg.ID)
	var i AtualizarCategoriaRow
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const atualizarProduto = `-- name: AtualizarProduto :one
UPDATE catalogo.produto
SET nome = $1, descricao = $2, preco_centavos = $3,
    imagem_url = $4, vendedor_id = $5, categoria_id = $6,
    ativo = $7, busca_normalizada = $8
WHERE id = $9
RETURNING id
`

type AtualizarProdutoParams struct {
	Nome             string
	Descricao        string
	PrecoCentavos    int64
	ImagemUrl        string
	VendedorID       pgtype.UUID
	CategoriaID      pgtype.UUID
	Ativo            bool
	BuscaNormalizada string
	ID               pgtype.UUID
}

// O Estoque total não está aqui: o ajuste depois da criação é da 3.4, com a
// guarda das Reservas. Desativar é este UPDATE de `ativo`, e quem esconde o
// Produto é a VIEW produto_visivel.
func (q *Queries) AtualizarProduto(ctx context.Context, arg AtualizarProdutoParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, atualizarProduto,
		arg.Nome,
		arg.Descricao,
		arg.PrecoCentavos,
		arg.ImagemUrl,
		arg.VendedorID,
		arg.CategoriaID,
		arg.Ativo,
		arg.BuscaNormalizada,
		arg.ID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const atualizarVendedor = `-- name: AtualizarVendedor :one
UPDATE catalogo.vendedor SET nome = $1, ativo = $2
WHERE id = $3
RETURNING id, nome, ativo
`

type AtualizarVendedorParams struct {
	Nome  string
	Ativo bool
	ID    pgtype.UUID
}

// Desativar é este UPDATE de `ativo`: nenhum Pedido é tocado, e quem esconde
// os Produtos é a VIEW produto_visivel.
func (q *Queries) AtualizarVendedor(ctx context.Context, arg AtualizarVendedorParams) (CatalogoVendedor, error) {
	row := q.db.QueryRow(ctx, atualizarVendedor, arg.Nome, arg.Ativo, arg.ID)
	var i CatalogoVendedor
	err := row.Scan(&i.ID, &i.Nome, &i.Ativo)
	return i, err
}

const baixarEstoqueTotal = `-- name: BaixarEstoqueTotal :exec
UPDATE catalogo.produto
SET estoque_total = estoque_total - $1
WHERE id = $2
`

type BaixarEstoqueTotalParams struct {
	Quantidade int32
	ProdutoID  pgtype.UUID
}

// A baixa é uma por Produto, e quem as ordena por identificador é o Go: o
// UPDATE … RETURNING não aceita ORDER BY, e a ordem é a mesma disciplina do
// `ORDER BY id FOR UPDATE` do Reservar — dois Pedidos com os mesmos Produtos
// em ordem inversa travariam um no outro. O CHECK (estoque_total >= 0) da
// migração é quem barra a baixa a mais.
func (q *Queries) BaixarEstoqueTotal(ctx context.Context, arg BaixarEstoqueTotalParams) error {
	_, err := q.db.Exec(ctx, baixarEstoqueTotal, arg.Quantidade, arg.ProdutoID)
	return err
}

const buscarProdutoAdmin = `-- name: BuscarProdutoAdmin :one
SELECT p.id, p.nome, p.descricao, p.preco_centavos, p.imagem_url,
       p.estoque_total, p.ativo,
       v.id AS vendedor_id, v.nome AS vendedor_nome,
       c.id AS categoria_id, c.nome AS categoria_nome
FROM catalogo.produto p
JOIN catalogo.vendedor v ON v.id = p.vendedor_id
JOIN catalogo.categoria c ON c.id = p.categoria_id
WHERE p.id = $1
`

type BuscarProdutoAdminRow struct {
	ID            pgtype.UUID
	Nome          string
	Descricao     string
	PrecoCentavos int64
	ImagemUrl     string
	EstoqueTotal  int32
	Ativo         bool
	VendedorID    pgtype.UUID
	VendedorNome  string
	CategoriaID   pgtype.UUID
	CategoriaNome string
}

// A linha que o criar e o editar devolvem, com os nomes de Vendedor e
// Categoria da listagem.
func (q *Queries) BuscarProdutoAdmin(ctx context.Context, id pgtype.UUID) (BuscarProdutoAdminRow, error) {
	row := q.db.QueryRow(ctx, buscarProdutoAdmin, id)
	var i BuscarProdutoAdminRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.PrecoCentavos,
		&i.ImagemUrl,
		&i.EstoqueTotal,
		&i.Ativo,
		&i.VendedorID,
		&i.VendedorNome,
		&i.CategoriaID,
		&i.CategoriaNome,
	)
	return i, err
}

const buscarProdutoComVendedor = `-- name: BuscarProdutoComVendedor :one
SELECT id, nome, descricao, preco_centavos, imagem_url, vendedor_nome
FROM catalogo.produto_visivel
WHERE id = $1
`

type BuscarProdutoComVendedorRow struct {
	ID            pgtype.UUID
	Nome          string
	Descricao     string
	PrecoCentavos int64
	ImagemUrl     string
	VendedorNome  string
}

// A consulta da Página de Produto (FR-9). Lê da VIEW do AD-19: Produto de
// Vendedor desativado sai daqui como zero linhas, o mesmo 404 do inexistente.
// `busca_normalizada` fica de fora: é dado de índice.
func (q *Queries) BuscarProdutoComVendedor(ctx context.Context, id pgtype.UUID) (BuscarProdutoComVendedorRow, error) {
	row := q.db.QueryRow(ctx, buscarProdutoComVendedor, id)
	var i BuscarProdutoComVendedorRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.PrecoCentavos,
		&i.ImagemUrl,
		&i.VendedorNome,
	)
	return i, err
}

const consolidarReservasDoPedido = `-- name: ConsolidarReservasDoPedido :many
UPDATE catalogo.reserva_estoque
SET estado = 'CONSOLIDADA'
WHERE pedido_id = $1 AND estado = 'ATIVA'
RETURNING produto_id, quantidade
`

type ConsolidarReservasDoPedidoRow struct {
	ProdutoID  pgtype.UUID
	Quantidade int32
}

// As duas consultas da consolidação (Estória 1.8), a única passagem em que o
// Estoque total muda. O `estado = 'ATIVA'` no WHERE é compare-and-swap como o
// do Status: zero linhas devolvidas é Reserva já consolidada, que é no-op e
// nunca erro.
func (q *Queries) ConsolidarReservasDoPedido(ctx context.Context, pedidoID pgtype.UUID) ([]ConsolidarReservasDoPedidoRow, error) {
	rows, err := q.db.Query(ctx, consolidarReservasDoPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsolidarReservasDoPedidoRow
	for rows.Next() {
		var i ConsolidarReservasDoPedidoRow
		if err := rows.Scan(&i.ProdutoID, &i.Quantidade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contarProdutos = `-- name: ContarProdutos :one
SELECT count(*) FROM catalogo.produto
`

func (q *Queries) ContarProdutos(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarProdutos)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarProdutosDaCategoria = `-- name: ContarProdutosDaCategoria :one
SELECT count(*) FROM catalogo.produto WHERE categoria_id = $1
`

// Só depois do 23503: a recusa diz quantos Produtos estão vinculados, e o
// caminho comum (remover Categoria vazia) continua sendo uma ida ao banco.
func (q *Queries) ContarProdutosDaCategoria(ctx context.Context, categoriaID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarProdutosDaCategoria, categoriaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarCategoria = `-- name: CriarCategoria :one
INSERT INTO catalogo.categoria (nome) VALUES ($1)
RETURNING id, nome
`

type CriarCategoriaRow struct {
	ID   pgtype.UUID
	Nome string
}

// Nome duplicado é decidido pelo UNIQUE (23505), nunca por SELECT antes.
func (q *Queries) CriarCategoria(ctx context.Context, nome string) (CriarCategoriaRow, error) {
	row := q.db.QueryRow(ctx, criarCategoria, nome)
	var i CriarCategoriaRow
	err := row.Scan(&i.ID, &i.Nome)
	return i, err
}

const criarProduto = `-- name: CriarProduto :one
INSERT INTO catalogo.produto
    (nome, descricao, preco_centavos, imagem_url, vendedor_id, categoria_id, estoque_total, busca_normalizada)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id
`

type CriarProdutoParams struct {
	Nome             string
	Descricao        string
	PrecoCentavos    int64
	ImagemUrl        string
	VendedorID       pgtype.UUID
	CategoriaID      pgtype.UUID
	EstoqueTotal     int32
	BuscaNormalizada string
}

// Vendedor ou Categoria inexistente é decidido pelas FKs (23503), e o nome da
// constraint diz qual campo errou. `busca_normalizada` vem do Go.
func (q *Queries) CriarProduto(ctx context.Context, arg CriarProdutoParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, criarProduto,
		arg.Nome,
		arg.Descricao,
		arg.PrecoCentavos,
		arg.ImagemUrl,
		arg.VendedorID,
		arg.CategoriaID,
		arg.EstoqueTotal,
		arg.BuscaNormalizada,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const criarReservaAtiva = `-- name: CriarReservaAtiva :exec
INSERT INTO catalogo.reserva_estoque (produto_id, pedido_id, quantidade, estado)
VALUES ($1, $2, $3, 'ATIVA')
`

type CriarReservaAtivaParams struct {
	ProdutoID  pgtype.UUID
	PedidoID   pgtype.UUID
	Quantidade int32
}

func (q *Queries) CriarReservaAtiva(ctx context.Context, arg CriarReservaAtivaParams) error {
	_, err := q.db.Exec(ctx, criarReservaAtiva, arg.ProdutoID, arg.PedidoID, arg.Quantidade)
	return err
}

const criarVendedor = `-- name: CriarVendedor :one
INSERT INTO catalogo.vendedor (nome) VALUES ($1)
RETURNING id, nome, ativo
`

// Nome duplicado é decidido pelo UNIQUE (23505), nunca por SELECT antes.
func (q *Queries) CriarVendedor(ctx context.Context, nome string) (CatalogoVendedor, error) {
	row := q.db.QueryRow(ctx, criarVendedor, nome)
	var i CatalogoVendedor
	err := row.Scan(&i.ID, &i.Nome, &i.Ativo)
	return i, err
}

const listarCategorias = `-- name: ListarCategorias :many
SELECT id, nome FROM catalogo.categoria ORDER BY nome, id
`

type ListarCategoriasRow struct {
	ID   pgtype.UUID
	Nome string
}

// A gestão de Categorias (3.2). `categoria_pai_id` não sai daqui: a Categoria
// é plana, e a coluna existe nula e não exposta.
func (q *Queries) ListarCategorias(ctx context.Context) ([]ListarCategoriasRow, error) {
	rows, err := q.db.Query(ctx, listarCategorias)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarCategoriasRow
	for rows.Next() {
		var i ListarCategoriasRow
		if err := rows.Scan(&i.ID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarProdutosAdmin = `-- name: ListarProdutosAdmin :many
SELECT p.id, p.nome, p.descricao, p.preco_centavos, p.imagem_url,
       p.estoque_total, p.ativo,
       v.id AS vendedor_id, v.nome AS vendedor_nome,
       c.id AS categoria_id, c.nome AS categoria_nome
FROM catalogo.produto p
JOIN catalogo.vendedor v ON v.id = p.vendedor_id
JOIN catalogo.categoria c ON c.id = p.categoria_id
ORDER BY p.nome, p.id
LIMIT $2 OFFSET $1
`

type ListarProdutosAdminParams struct {
	Deslocamento int32
	Limite       int32
}

type ListarProdutosAdminRow struct {
	ID            pgtype.UUID
	Nome          string
	Descricao     string
	PrecoCentavos int64
	ImagemUrl     string
	EstoqueTotal  int32
	Ativo         bool
	VendedorID    pgtype.UUID
	VendedorNome  string
	CategoriaID   pgtype.UUID
	CategoriaNome string
}

// A listagem administrativa de Produto (3.3, AD-16 emendado): é do
// `catalogo`, e traz ativos e inativos — a VIEW de `busca` só enxerga Produto
// visível. Desempate sempre em id (AD-18).
func (q *Queries) ListarProdutosAdmin(ctx context.Context, arg ListarProdutosAdminParams) ([]ListarProdutosAdminRow, error) {
	rows, err := q.db.Query(ctx, listarProdutosAdmin, arg.Deslocamento, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarProdutosAdminRow
	for rows.Next() {
		var i ListarProdutosAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.PrecoCentavos,
			&i.ImagemUrl,
			&i.EstoqueTotal,
			&i.Ativo,
			&i.VendedorID,
			&i.VendedorNome,
			&i.CategoriaID,
			&i.CategoriaNome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarVendedores = `-- name: ListarVendedores :many
SELECT id, nome, ativo FROM catalogo.vendedor ORDER BY nome, id
`

// A gestão de Vendedores (3.1). A lista traz ativos e inativos — é a tela do
// Administrador, e não a loja — por nome, com desempate estável por id.
func (q *Queries) ListarVendedores(ctx context.Context) ([]CatalogoVendedor, error) {
	rows, err := q.db.Query(ctx, listarVendedores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogoVendedor
	for rows.Next() {
		var i CatalogoVendedor
		if err := rows.Scan(&i.ID, &i.Nome, &i.Ativo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerCategoria = `-- name: RemoverCategoria :execrows
DELETE FROM catalogo.categoria WHERE id = $1
`

// Categoria com Produto é barrada pela FK `produto.categoria_id` (23503).
func (q *Queries) RemoverCategoria(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removerCategoria, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const removerVendedor = `-- name: RemoverVendedor :execrows
DELETE FROM catalogo.vendedor WHERE id = $1
`

// Vendedor com Produto é barrado pela FK `produto.vendedor_id` (23503), sem
// contagem antes.
func (q *Queries) RemoverVendedor(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removerVendedor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const somarReservasAtivas = `-- name: SomarReservasAtivas :one
SELECT coalesce(sum(quantidade), 0)::bigint AS reservado
FROM catalogo.reserva_estoque
WHERE produto_id = $1 AND estado = 'ATIVA'
`

// Só depois a soma. Com a trava segura, nenhuma Reserva nova entra entre a
// soma e o INSERT que a sucede.
func (q *Queries) SomarReservasAtivas(ctx context.Context, produtoID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, somarReservasAtivas, produtoID)
	var reservado int64
	err := row.Scan(&reservado)
	return reservado, err
}

const travarProdutosParaReserva = `-- name: TravarProdutosParaReserva :many
SELECT p.id, p.estoque_total
FROM catalogo.produto p
WHERE p.id = ANY($1::uuid[])
  AND p.id IN (SELECT id FROM catalogo.produto_visivel)
ORDER BY p.id
FOR UPDATE OF p
`

type TravarProdutosParaReservaRow struct {
	ID           pgtype.UUID
	EstoqueTotal int32
}

// As duas consultas abaixo são o AD-5, e são duas de propósito: é a ordem
// entre elas que protege o Estoque. Uma consulta só não teria como errá-la —
// e errá-la é vender a mesma última unidade duas vezes.
//
// Primeiro a trava. O `ORDER BY id` não é estilo: sem ele, dois Pedidos com os
// mesmos dois Produtos em ordem inversa travam um no outro.
//
// A visibilidade entra na mesma consulta, por subconsulta à VIEW, e a trava é
// `OF p`: `FOR UPDATE` sobre a VIEW travaria também a linha do Vendedor, e
// Pedidos de Produtos diferentes do mesmo Vendedor esperariam um pelo outro.
func (q *Queries) TravarProdutosParaReserva(ctx context.Context, ids []pgtype.UUID) ([]TravarProdutosParaReservaRow, error) {
	rows, err := q.db.Query(ctx, travarProdutosParaReserva, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravarProdutosParaReservaRow
	for rows.Next() {
		var i TravarProdutosParaReservaRow
		if err := rows.Scan(&i.ID, &i.EstoqueTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
