// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const atualizarVendedor = `-- name: AtualizarVendedor :one
UPDATE catalogo.vendedor SET nome = $1, ativo = $2
WHERE id = $3
RETURNING id, nome, ativo
`

type AtualizarVendedorParams struct {
	Nome  string
	Ativo bool
	ID    pgtype.UUID
}

// Desativar é este UPDATE de `ativo`: nenhum Pedido é tocado, e quem esconde
// os Produtos é a VIEW produto_visivel.
func (q *Queries) AtualizarVendedor(ctx context.Context, arg AtualizarVendedorParams) (CatalogoVendedor, error) {
	row := q.db.QueryRow(ctx, atualizarVendedor, arg.Nome, arg.Ativo, arg.ID)
	var i CatalogoVendedor
	err := row.Scan(&i.ID, &i.Nome, &i.Ativo)
	return i, err
}

const baixarEstoqueTotal = `-- name: BaixarEstoqueTotal :exec
UPDATE catalogo.produto
SET estoque_total = estoque_total - $1
WHERE id = $2
`

type BaixarEstoqueTotalParams struct {
	Quantidade int32
	ProdutoID  pgtype.UUID
}

// A baixa é uma por Produto, e quem as ordena por identificador é o Go: o
// UPDATE … RETURNING não aceita ORDER BY, e a ordem é a mesma disciplina do
// `ORDER BY id FOR UPDATE` do Reservar — dois Pedidos com os mesmos Produtos
// em ordem inversa travariam um no outro. O CHECK (estoque_total >= 0) da
// migração é quem barra a baixa a mais.
func (q *Queries) BaixarEstoqueTotal(ctx context.Context, arg BaixarEstoqueTotalParams) error {
	_, err := q.db.Exec(ctx, baixarEstoqueTotal, arg.Quantidade, arg.ProdutoID)
	return err
}

const buscarProdutoComVendedor = `-- name: BuscarProdutoComVendedor :one
SELECT id, nome, descricao, preco_centavos, imagem_url, vendedor_nome
FROM catalogo.produto_visivel
WHERE id = $1
`

type BuscarProdutoComVendedorRow struct {
	ID            pgtype.UUID
	Nome          string
	Descricao     string
	PrecoCentavos int64
	ImagemUrl     string
	VendedorNome  string
}

// A consulta da Página de Produto (FR-9). Lê da VIEW do AD-19: Produto de
// Vendedor desativado sai daqui como zero linhas, o mesmo 404 do inexistente.
// `busca_normalizada` fica de fora: é dado de índice.
func (q *Queries) BuscarProdutoComVendedor(ctx context.Context, id pgtype.UUID) (BuscarProdutoComVendedorRow, error) {
	row := q.db.QueryRow(ctx, buscarProdutoComVendedor, id)
	var i BuscarProdutoComVendedorRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.PrecoCentavos,
		&i.ImagemUrl,
		&i.VendedorNome,
	)
	return i, err
}

const consolidarReservasDoPedido = `-- name: ConsolidarReservasDoPedido :many
UPDATE catalogo.reserva_estoque
SET estado = 'CONSOLIDADA'
WHERE pedido_id = $1 AND estado = 'ATIVA'
RETURNING produto_id, quantidade
`

type ConsolidarReservasDoPedidoRow struct {
	ProdutoID  pgtype.UUID
	Quantidade int32
}

// As duas consultas da consolidação (Estória 1.8), a única passagem em que o
// Estoque total muda. O `estado = 'ATIVA'` no WHERE é compare-and-swap como o
// do Status: zero linhas devolvidas é Reserva já consolidada, que é no-op e
// nunca erro.
func (q *Queries) ConsolidarReservasDoPedido(ctx context.Context, pedidoID pgtype.UUID) ([]ConsolidarReservasDoPedidoRow, error) {
	rows, err := q.db.Query(ctx, consolidarReservasDoPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsolidarReservasDoPedidoRow
	for rows.Next() {
		var i ConsolidarReservasDoPedidoRow
		if err := rows.Scan(&i.ProdutoID, &i.Quantidade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const criarReservaAtiva = `-- name: CriarReservaAtiva :exec
INSERT INTO catalogo.reserva_estoque (produto_id, pedido_id, quantidade, estado)
VALUES ($1, $2, $3, 'ATIVA')
`

type CriarReservaAtivaParams struct {
	ProdutoID  pgtype.UUID
	PedidoID   pgtype.UUID
	Quantidade int32
}

func (q *Queries) CriarReservaAtiva(ctx context.Context, arg CriarReservaAtivaParams) error {
	_, err := q.db.Exec(ctx, criarReservaAtiva, arg.ProdutoID, arg.PedidoID, arg.Quantidade)
	return err
}

const criarVendedor = `-- name: CriarVendedor :one
INSERT INTO catalogo.vendedor (nome) VALUES ($1)
RETURNING id, nome, ativo
`

// Nome duplicado é decidido pelo UNIQUE (23505), nunca por SELECT antes.
func (q *Queries) CriarVendedor(ctx context.Context, nome string) (CatalogoVendedor, error) {
	row := q.db.QueryRow(ctx, criarVendedor, nome)
	var i CatalogoVendedor
	err := row.Scan(&i.ID, &i.Nome, &i.Ativo)
	return i, err
}

const listarVendedores = `-- name: ListarVendedores :many
SELECT id, nome, ativo FROM catalogo.vendedor ORDER BY nome, id
`

// A gestão de Vendedores (3.1). A lista traz ativos e inativos — é a tela do
// Administrador, e não a loja — por nome, com desempate estável por id.
func (q *Queries) ListarVendedores(ctx context.Context) ([]CatalogoVendedor, error) {
	rows, err := q.db.Query(ctx, listarVendedores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogoVendedor
	for rows.Next() {
		var i CatalogoVendedor
		if err := rows.Scan(&i.ID, &i.Nome, &i.Ativo); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerVendedor = `-- name: RemoverVendedor :execrows
DELETE FROM catalogo.vendedor WHERE id = $1
`

// Vendedor com Produto é barrado pela FK `produto.vendedor_id` (23503), sem
// contagem antes.
func (q *Queries) RemoverVendedor(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, removerVendedor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const somarReservasAtivas = `-- name: SomarReservasAtivas :one
SELECT coalesce(sum(quantidade), 0)::bigint AS reservado
FROM catalogo.reserva_estoque
WHERE produto_id = $1 AND estado = 'ATIVA'
`

// Só depois a soma. Com a trava segura, nenhuma Reserva nova entra entre a
// soma e o INSERT que a sucede.
func (q *Queries) SomarReservasAtivas(ctx context.Context, produtoID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, somarReservasAtivas, produtoID)
	var reservado int64
	err := row.Scan(&reservado)
	return reservado, err
}

const travarProdutosParaReserva = `-- name: TravarProdutosParaReserva :many
SELECT p.id, p.estoque_total
FROM catalogo.produto p
WHERE p.id = ANY($1::uuid[])
  AND p.id IN (SELECT id FROM catalogo.produto_visivel)
ORDER BY p.id
FOR UPDATE OF p
`

type TravarProdutosParaReservaRow struct {
	ID           pgtype.UUID
	EstoqueTotal int32
}

// As duas consultas abaixo são o AD-5, e são duas de propósito: é a ordem
// entre elas que protege o Estoque. Uma consulta só não teria como errá-la —
// e errá-la é vender a mesma última unidade duas vezes.
//
// Primeiro a trava. O `ORDER BY id` não é estilo: sem ele, dois Pedidos com os
// mesmos dois Produtos em ordem inversa travam um no outro.
//
// A visibilidade entra na mesma consulta, por subconsulta à VIEW, e a trava é
// `OF p`: `FOR UPDATE` sobre a VIEW travaria também a linha do Vendedor, e
// Pedidos de Produtos diferentes do mesmo Vendedor esperariam um pelo outro.
func (q *Queries) TravarProdutosParaReserva(ctx context.Context, ids []pgtype.UUID) ([]TravarProdutosParaReservaRow, error) {
	rows, err := q.db.Query(ctx, travarProdutosParaReserva, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TravarProdutosParaReservaRow
	for rows.Next() {
		var i TravarProdutosParaReservaRow
		if err := rows.Scan(&i.ID, &i.EstoqueTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
