// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gerado

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatalogoCategoria struct {
	ID             pgtype.UUID
	Nome           string
	CategoriaPaiID pgtype.UUID
}

type CatalogoProduto struct {
	ID               pgtype.UUID
	Nome             string
	Descricao        string
	PrecoCentavos    int64
	ImagemUrl        string
	VendedorID       pgtype.UUID
	CategoriaID      pgtype.UUID
	BuscaNormalizada string
}

type CatalogoVendedor struct {
	ID    pgtype.UUID
	Nome  string
	Ativo bool
}
