// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const avancarStatus = `-- name: AvancarStatus :execrows
UPDATE pedido.pedido SET status = $1 WHERE id = $2 AND status = $3
`

type AvancarStatusParams struct {
	Para     string
	PedidoID pgtype.UUID
	De       string
}

// O único ponto de mutação do Status (AD-6), e é compare-and-swap: o estado de
// origem entra no WHERE, e zero linhas afetadas significa "o estado já
// avançou", nunca "o Pedido não existe" — as duas coisas são o mesmo desfecho
// esperado para quem chama.
func (q *Queries) AvancarStatus(ctx context.Context, arg AvancarStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, avancarStatus, arg.Para, arg.PedidoID, arg.De)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const criarItemPedido = `-- name: CriarItemPedido :exec
INSERT INTO pedido.item_pedido
    (pedido_id, produto_id, nome, vendedor_nome, preco_praticado_centavos, quantidade)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CriarItemPedidoParams struct {
	PedidoID               pgtype.UUID
	ProdutoID              pgtype.UUID
	Nome                   string
	VendedorNome           string
	PrecoPraticadoCentavos int64
	Quantidade             int32
}

// O Item congela o que era verdade no instante da compra: nome, preço
// praticado e Vendedor são cópia, e não referência.
func (q *Queries) CriarItemPedido(ctx context.Context, arg CriarItemPedidoParams) error {
	_, err := q.db.Exec(ctx, criarItemPedido,
		arg.PedidoID,
		arg.ProdutoID,
		arg.Nome,
		arg.VendedorNome,
		arg.PrecoPraticadoCentavos,
		arg.Quantidade,
	)
	return err
}

const criarPedido = `-- name: CriarPedido :one
INSERT INTO pedido.pedido (numero, comprador_id, status, total_centavos)
VALUES ($1, $2, $3, $4)
RETURNING id, numero, status, total_centavos
`

type CriarPedidoParams struct {
	Numero        string
	CompradorID   pgtype.UUID
	Status        string
	TotalCentavos int64
}

type CriarPedidoRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
}

func (q *Queries) CriarPedido(ctx context.Context, arg CriarPedidoParams) (CriarPedidoRow, error) {
	row := q.db.QueryRow(ctx, criarPedido,
		arg.Numero,
		arg.CompradorID,
		arg.Status,
		arg.TotalCentavos,
	)
	var i CriarPedidoRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.TotalCentavos,
	)
	return i, err
}

const proximoNumeroDoAno = `-- name: ProximoNumeroDoAno :one

INSERT INTO pedido.contador_numero (ano, ultimo) VALUES ($1, 1)
ON CONFLICT (ano) DO UPDATE SET ultimo = contador_numero.ultimo + 1
RETURNING ultimo
`

// As consultas do caso de uso "um Pedido nasce em AGUARDANDO_PAGAMENTO".
// Todas rodam dentro da mesma transação, passada como `tx pgx.Tx` (AD-4).
// O contador por ano resolve o número legível na própria transação: sem DDL em
// tempo de execução e sem buraco na numeração quando a transação é revertida.
// O `contador_numero` do SET é a linha em conflito — dentro do ON CONFLICT o
// nome da tabela é o apelido, e qualificá-lo pelo schema seria erro de sintaxe.
func (q *Queries) ProximoNumeroDoAno(ctx context.Context, ano int32) (int64, error) {
	row := q.db.QueryRow(ctx, proximoNumeroDoAno, ano)
	var ultimo int64
	err := row.Scan(&ultimo)
	return ultimo, err
}

const registrarTransicao = `-- name: RegistrarTransicao :exec
INSERT INTO pedido.transicao_status (pedido_id, status_anterior, status_novo, autor)
VALUES ($1, $2, $3, $4)
`

type RegistrarTransicaoParams struct {
	PedidoID       pgtype.UUID
	StatusAnterior string
	StatusNovo     string
	Autor          string
}

func (q *Queries) RegistrarTransicao(ctx context.Context, arg RegistrarTransicaoParams) error {
	_, err := q.db.Exec(ctx, registrarTransicao,
		arg.PedidoID,
		arg.StatusAnterior,
		arg.StatusNovo,
		arg.Autor,
	)
	return err
}
