// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const avancarStatus = `-- name: AvancarStatus :execrows
UPDATE pedido.pedido SET status = $1 WHERE id = $2 AND status = $3
`

type AvancarStatusParams struct {
	Para     string
	PedidoID pgtype.UUID
	De       string
}

// O único ponto de mutação do Status (AD-6), e é compare-and-swap: o estado de
// origem entra no WHERE, e zero linhas afetadas significa "o estado já
// avançou", nunca "o Pedido não existe" — as duas coisas são o mesmo desfecho
// esperado para quem chama.
func (q *Queries) AvancarStatus(ctx context.Context, arg AvancarStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, avancarStatus, arg.Para, arg.PedidoID, arg.De)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarPedidoDoComprador = `-- name: BuscarPedidoDoComprador :one
SELECT p.id, p.numero, p.status, p.subtotal_centavos, p.frete_centavos, p.total_centavos,
       p.endereco_destinatario, p.endereco_cep, p.endereco_logradouro, p.endereco_numero,
       p.endereco_complemento, p.endereco_bairro, p.endereco_cidade, p.endereco_uf,
       -- O cast é carga: sem ele o sqlc não infere o tipo da subconsulta e
       -- devolve ` + "`" + `interface{}` + "`" + `, que só falharia no Scan em tempo de execução.
       (SELECT max(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id)::timestamptz AS atualizado_em
FROM pedido.pedido p
WHERE p.id = $1 AND p.comprador_id = $2
`

type BuscarPedidoDoCompradorParams struct {
	PedidoID    pgtype.UUID
	CompradorID pgtype.UUID
}

type BuscarPedidoDoCompradorRow struct {
	ID                   pgtype.UUID
	Numero               string
	Status               string
	SubtotalCentavos     int64
	FreteCentavos        int64
	TotalCentavos        int64
	EnderecoDestinatario pgtype.Text
	EnderecoCep          pgtype.Text
	EnderecoLogradouro   pgtype.Text
	EnderecoNumero       pgtype.Text
	EnderecoComplemento  pgtype.Text
	EnderecoBairro       pgtype.Text
	EnderecoCidade       pgtype.Text
	EnderecoUf           pgtype.Text
	AtualizadoEm         pgtype.Timestamptz
}

// A leitura da tela de acompanhamento. O dono entra no WHERE, e não numa
// checagem depois: Pedido de outro Comprador e Pedido inexistente saem os dois
// como "nenhuma linha", que é o mesmo 404 — não vaza existência.
// O instante é o da última transição, absoluto e vindo do servidor: o
// navegador nunca conta duração.
// Subtotal, Frete e Endereço são os congelados da 5.6: a tela os exibe como
// foram gravados, e não os recompõe (AD-9). O Endereço é todo nulo no Pedido
// do esqueleto — o CHECK `pedido_criacao_completa` garante que nunca pela metade.
func (q *Queries) BuscarPedidoDoComprador(ctx context.Context, arg BuscarPedidoDoCompradorParams) (BuscarPedidoDoCompradorRow, error) {
	row := q.db.QueryRow(ctx, buscarPedidoDoComprador, arg.PedidoID, arg.CompradorID)
	var i BuscarPedidoDoCompradorRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.SubtotalCentavos,
		&i.FreteCentavos,
		&i.TotalCentavos,
		&i.EnderecoDestinatario,
		&i.EnderecoCep,
		&i.EnderecoLogradouro,
		&i.EnderecoNumero,
		&i.EnderecoComplemento,
		&i.EnderecoBairro,
		&i.EnderecoCidade,
		&i.EnderecoUf,
		&i.AtualizadoEm,
	)
	return i, err
}

const buscarPedidoParaAdministrador = `-- name: BuscarPedidoParaAdministrador :one
SELECT p.id, p.numero, p.status, p.comprador_id,
       p.subtotal_centavos, p.frete_centavos, p.total_centavos,
       p.endereco_destinatario, p.endereco_cep, p.endereco_logradouro, p.endereco_numero,
       p.endereco_complemento, p.endereco_bairro, p.endereco_cidade, p.endereco_uf,
       -- O cast é carga, pelo mesmo motivo de BuscarPedidoDoComprador.
       (SELECT max(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id)::timestamptz AS atualizado_em
FROM pedido.pedido p
WHERE p.id = $1
`

type BuscarPedidoParaAdministradorRow struct {
	ID                   pgtype.UUID
	Numero               string
	Status               string
	CompradorID          pgtype.UUID
	SubtotalCentavos     int64
	FreteCentavos        int64
	TotalCentavos        int64
	EnderecoDestinatario pgtype.Text
	EnderecoCep          pgtype.Text
	EnderecoLogradouro   pgtype.Text
	EnderecoNumero       pgtype.Text
	EnderecoComplemento  pgtype.Text
	EnderecoBairro       pgtype.Text
	EnderecoCidade       pgtype.Text
	EnderecoUf           pgtype.Text
	AtualizadoEm         pgtype.Timestamptz
}

// O Detalhe administrativo (6.4). É BuscarPedidoDoComprador sem o dono no
// WHERE e com o `comprador_id` a mais: o Administrador vê o Pedido de
// qualquer Comprador, e é por esse identificador que `identidade` devolve o
// nome e o e-mail de quem comprou.
//
// Consulta própria, e não um parâmetro nulo em BuscarPedidoDoComprador: o
// dono no WHERE é a garantia do AD-11, e um `@comprador_id IS NULL OR …`
// deixaria a leitura do Comprador a uma linha de distância de virar leitura
// de todo mundo.
func (q *Queries) BuscarPedidoParaAdministrador(ctx context.Context, pedidoID pgtype.UUID) (BuscarPedidoParaAdministradorRow, error) {
	row := q.db.QueryRow(ctx, buscarPedidoParaAdministrador, pedidoID)
	var i BuscarPedidoParaAdministradorRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.CompradorID,
		&i.SubtotalCentavos,
		&i.FreteCentavos,
		&i.TotalCentavos,
		&i.EnderecoDestinatario,
		&i.EnderecoCep,
		&i.EnderecoLogradouro,
		&i.EnderecoNumero,
		&i.EnderecoComplemento,
		&i.EnderecoBairro,
		&i.EnderecoCidade,
		&i.EnderecoUf,
		&i.AtualizadoEm,
	)
	return i, err
}

const contarPedidosAdmin = `-- name: ContarPedidosAdmin :one
SELECT count(*)
FROM pedido.pedido p
WHERE ($1::text IS NULL OR p.status = $1::text)
`

// O total da mesma listagem, com o WHERE dela palavra por palavra: um filtro
// que divergisse aqui paginaria sobre um total que não é o da lista.
func (q *Queries) ContarPedidosAdmin(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, contarPedidosAdmin, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarPedidosDoComprador = `-- name: ContarPedidosDoComprador :one
SELECT count(*)
FROM pedido.pedido p
WHERE p.comprador_id = $1
`

// O total da mesma listagem, com o WHERE dela palavra por palavra: um filtro
// que divergisse aqui paginaria sobre um total que não é o da lista.
func (q *Queries) ContarPedidosDoComprador(ctx context.Context, compradorID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarPedidosDoComprador, compradorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarItemPedido = `-- name: CriarItemPedido :exec
INSERT INTO pedido.item_pedido
    (pedido_id, produto_id, nome, vendedor_nome, preco_praticado_centavos, quantidade)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CriarItemPedidoParams struct {
	PedidoID               pgtype.UUID
	ProdutoID              pgtype.UUID
	Nome                   string
	VendedorNome           string
	PrecoPraticadoCentavos int64
	Quantidade             int32
}

// O Item congela o que era verdade no instante da compra: nome, preço
// praticado e Vendedor são cópia, e não referência.
func (q *Queries) CriarItemPedido(ctx context.Context, arg CriarItemPedidoParams) error {
	_, err := q.db.Exec(ctx, criarItemPedido,
		arg.PedidoID,
		arg.ProdutoID,
		arg.Nome,
		arg.VendedorNome,
		arg.PrecoPraticadoCentavos,
		arg.Quantidade,
	)
	return err
}

const criarPedido = `-- name: CriarPedido :one
INSERT INTO pedido.pedido (
    numero, comprador_id, status, subtotal_centavos, frete_centavos, total_centavos,
    endereco_destinatario, endereco_cep, endereco_logradouro, endereco_numero,
    endereco_complemento, endereco_bairro, endereco_cidade, endereco_uf,
    chave_idempotencia, digest_corpo
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14,
    $15, $16
)
ON CONFLICT (comprador_id, chave_idempotencia) DO NOTHING
RETURNING id, numero, status, total_centavos
`

type CriarPedidoParams struct {
	Numero               string
	CompradorID          pgtype.UUID
	Status               string
	SubtotalCentavos     int64
	FreteCentavos        int64
	TotalCentavos        int64
	EnderecoDestinatario pgtype.Text
	EnderecoCep          pgtype.Text
	EnderecoLogradouro   pgtype.Text
	EnderecoNumero       pgtype.Text
	EnderecoComplemento  pgtype.Text
	EnderecoBairro       pgtype.Text
	EnderecoCidade       pgtype.Text
	EnderecoUf           pgtype.Text
	ChaveIdempotencia    pgtype.UUID
	DigestCorpo          pgtype.Text
}

type CriarPedidoRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
}

// O INSERT é a reivindicação da `Idempotency-Key` (AD-7): o gêmeo concorrente
// espera no índice único (comprador_id, chave_idempotencia) e, quando o
// primeiro comita, cai no DO NOTHING — zero linhas, que `pedido` traduz em
// releitura por PedidoPorChave. O 23505 nunca chega a existir, e por isso
// nunca chega ao navegador. Tudo que o Pedido congela está aqui, e o gatilho
// da 5.1 impede reescrever depois.
func (q *Queries) CriarPedido(ctx context.Context, arg CriarPedidoParams) (CriarPedidoRow, error) {
	row := q.db.QueryRow(ctx, criarPedido,
		arg.Numero,
		arg.CompradorID,
		arg.Status,
		arg.SubtotalCentavos,
		arg.FreteCentavos,
		arg.TotalCentavos,
		arg.EnderecoDestinatario,
		arg.EnderecoCep,
		arg.EnderecoLogradouro,
		arg.EnderecoNumero,
		arg.EnderecoComplemento,
		arg.EnderecoBairro,
		arg.EnderecoCidade,
		arg.EnderecoUf,
		arg.ChaveIdempotencia,
		arg.DigestCorpo,
	)
	var i CriarPedidoRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.TotalCentavos,
	)
	return i, err
}

const historicoDoPedido = `-- name: HistoricoDoPedido :many
SELECT status_anterior, status_novo, ator, motivo, ocorrido_em
FROM pedido.transicao_status
WHERE pedido_id = $1
ORDER BY ocorrido_em, id
`

type HistoricoDoPedidoRow struct {
	StatusAnterior string
	StatusNovo     string
	Ator           string
	Motivo         pgtype.Text
	OcorridoEm     pgtype.Timestamptz
}

// O histórico em ordem de acontecimento. O `id` desempata duas transições no
// mesmo instante: é uuidv7(), ordenado no tempo por construção.
func (q *Queries) HistoricoDoPedido(ctx context.Context, pedidoID pgtype.UUID) ([]HistoricoDoPedidoRow, error) {
	rows, err := q.db.Query(ctx, historicoDoPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoricoDoPedidoRow
	for rows.Next() {
		var i HistoricoDoPedidoRow
		if err := rows.Scan(
			&i.StatusAnterior,
			&i.StatusNovo,
			&i.Ator,
			&i.Motivo,
			&i.OcorridoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itensDoPedido = `-- name: ItensDoPedido :many
SELECT produto_id, nome, vendedor_nome, preco_praticado_centavos, quantidade
FROM pedido.item_pedido
WHERE pedido_id = $1
ORDER BY id
`

type ItensDoPedidoRow struct {
	ProdutoID              pgtype.UUID
	Nome                   string
	VendedorNome           string
	PrecoPraticadoCentavos int64
	Quantidade             int32
}

// Os Itens de Pedido como a tela os mostra: o que foi congelado na compra,
// nunca o preço de hoje (FR-30). Sem dono no WHERE: quem chama já leu o
// Pedido pelo dono (AD-11). A ordem por `id` é a da criação — uuidv7().
// O `vendedor_nome` é o congelado na criação, como o `nome` e o preço: é o
// Vendedor que vendeu, e não o que hoje estaria ligado ao Produto. Sai nesta
// consulta, e não numa segunda só para o Administrador, porque a coluna já
// está na tabela e a linha já é lida — quem não o exibe (o Comprador) só não
// o serializa.
func (q *Queries) ItensDoPedido(ctx context.Context, pedidoID pgtype.UUID) ([]ItensDoPedidoRow, error) {
	rows, err := q.db.Query(ctx, itensDoPedido, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItensDoPedidoRow
	for rows.Next() {
		var i ItensDoPedidoRow
		if err := rows.Scan(
			&i.ProdutoID,
			&i.Nome,
			&i.VendedorNome,
			&i.PrecoPraticadoCentavos,
			&i.Quantidade,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itensParaReserva = `-- name: ItensParaReserva :many
SELECT produto_id, quantidade
FROM pedido.item_pedido
WHERE pedido_id = $1
ORDER BY produto_id
`

type ItensParaReservaRow struct {
	ProdutoID  pgtype.UUID
	Quantidade int32
}

// Os Itens do próprio Pedido, que é o que a nova Tentativa reserva de novo
// (AD-3): nada é remontado a partir do Carrinho.
func (q *Queries) ItensParaReserva(ctx context.Context, pedidoID pgtype.UUID) ([]ItensParaReservaRow, error) {
	rows, err := q.db.Query(ctx, itensParaReserva, pedidoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItensParaReservaRow
	for rows.Next() {
		var i ItensParaReservaRow
		if err := rows.Scan(&i.ProdutoID, &i.Quantidade); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarFaixasDeFrete = `-- name: ListarFaixasDeFrete :many
SELECT cep_inicio, cep_fim, regiao, valor_centavos, padrao
FROM pedido.faixa_frete
ORDER BY padrao, cep_inicio
`

type ListarFaixasDeFreteRow struct {
	CepInicio     pgtype.Text
	CepFim        pgtype.Text
	Regiao        string
	ValorCentavos int64
	Padrao        bool
}

// A Regra de Frete inteira (AD-17): são nove linhas, e a função pura escolhe.
// A padrão vem por último, e a ordem por `cep_inicio` torna a escolha
// determinística mesmo que alguém acrescente uma faixa sobreposta.
func (q *Queries) ListarFaixasDeFrete(ctx context.Context) ([]ListarFaixasDeFreteRow, error) {
	rows, err := q.db.Query(ctx, listarFaixasDeFrete)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarFaixasDeFreteRow
	for rows.Next() {
		var i ListarFaixasDeFreteRow
		if err := rows.Scan(
			&i.CepInicio,
			&i.CepFim,
			&i.Regiao,
			&i.ValorCentavos,
			&i.Padrao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosAdmin = `-- name: ListarPedidosAdmin :many
SELECT p.id, p.numero, p.status, p.total_centavos,
       (SELECT min(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id)::timestamptz AS criado_em
FROM pedido.pedido p
WHERE ($1::text IS NULL OR p.status = $1::text)
ORDER BY
  CASE WHEN $2::text = 'recentes'
       THEN (SELECT min(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id) END DESC NULLS LAST,
  CASE WHEN $2::text = 'antigos'
       THEN (SELECT min(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id) END ASC,
  p.id
LIMIT $4 OFFSET $3
`

type ListarPedidosAdminParams struct {
	Status       pgtype.Text
	Ordenacao    string
	Deslocamento int32
	Limite       int32
}

type ListarPedidosAdminRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
	CriadoEm      pgtype.Timestamptz
}

// A Tabela de Pedidos do Administrador (6.4): todos os Compradores, filtrável
// por Status e ordenável por data. Sem dono no WHERE — é justamente o que
// distingue esta listagem da do Comprador.
//
// O filtro é opcional por `IS NULL OR`, no molde de `busca`, e a data é o
// nascimento do histórico, como em ListarPedidosDoComprador — nenhuma coluna
// nova. A subconsulta se repete no ORDER BY porque o PostgreSQL não deixa
// usar o apelido da lista de seleção dentro de uma expressão.
//
// Uma chave por ordenação; a que não vale vira NULL e empata. `recentes` é
// DESC com NULLS LAST pelo motivo de ListarPedidosDoComprador, e o desempate
// final é sempre `id` (AD-18).
//
// ponytail: a subconsulta correlacionada sai TRÊS vezes por linha — uma na
// lista de seleção e uma em cada chave de ordenação —, sobre varredura
// sequencial de `pedido.pedido` sem o dono no WHERE que estreita a do
// Comprador. Teto: o índice `transicao_status (pedido_id, ocorrido_em)` da 5.1
// serve as três, e o volume do MVP (dezenas de Pedidos) as torna invisíveis; o
// que dói primeiro é a ordenação, que roda sobre a tabela inteira antes do
// LIMIT. A saída barata é uma `CROSS JOIN LATERAL` calculando `criado_em` uma
// vez e ordenando pela coluna dela; a cara, e que mentiria sobre os Pedidos já
// gravados, é `criado_em` denormalizado no Pedido.
func (q *Queries) ListarPedidosAdmin(ctx context.Context, arg ListarPedidosAdminParams) ([]ListarPedidosAdminRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosAdmin,
		arg.Status,
		arg.Ordenacao,
		arg.Deslocamento,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosAdminRow
	for rows.Next() {
		var i ListarPedidosAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Status,
			&i.TotalCentavos,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPedidosDoComprador = `-- name: ListarPedidosDoComprador :many
SELECT p.id, p.numero, p.status, p.total_centavos,
       (SELECT min(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id)::timestamptz AS criado_em
FROM pedido.pedido p
WHERE p.comprador_id = $1
ORDER BY criado_em DESC NULLS LAST, p.id DESC
LIMIT $3 OFFSET $2
`

type ListarPedidosDoCompradorParams struct {
	CompradorID  pgtype.UUID
	Deslocamento int32
	Limite       int32
}

type ListarPedidosDoCompradorRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
	CriadoEm      pgtype.Timestamptz
}

// A listagem da tela "Meus pedidos" (6.1). O dono entra no WHERE, e não numa
// checagem depois (AD-11): a rota nunca lê Pedido de outro Comprador para
// descartar depois.
//
// A data é o nascimento já gravado no histórico: `pedido.Criar` registra a
// primeira transição com `status_anterior` vazio na mesma transação do
// INSERT, então `min(ocorrido_em)` É o instante de nascimento, e não uma
// aproximação — nenhuma coluna nova, nenhuma migração. O cast é carga, pelo
// mesmo motivo de BuscarPedidoDoComprador: sem ele o sqlc devolve
// `interface{}` e a falha só apareceria no Scan.
//
// A ordem é o nascimento, do mais recente para o mais antigo, terminando em
// `id` para o OFFSET ser estável: duas transações concorrentes podem empatar
// no instante, e aí quem desempata é a chave — uuidv7(), já cronológica por
// construção. NULLS LAST porque DESC é NULLS FIRST no PostgreSQL: Pedido sem
// linha em transicao_status é inalcançável pelo aplicativo (Criar grava a
// primeira na mesma transação), mas se existisse iria ao topo da página 1 e
// sairia sem data nenhuma.
//
// ponytail: a subconsulta por linha na ordenação. O índice
// `transicao_status (pedido_id, ocorrido_em)` da 5.1 já a serve; o que
// pagaria mais é `criado_em` denormalizado no Pedido, e isso mentiria sobre
// os Pedidos já gravados.
func (q *Queries) ListarPedidosDoComprador(ctx context.Context, arg ListarPedidosDoCompradorParams) ([]ListarPedidosDoCompradorRow, error) {
	rows, err := q.db.Query(ctx, listarPedidosDoComprador, arg.CompradorID, arg.Deslocamento, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarPedidosDoCompradorRow
	for rows.Next() {
		var i ListarPedidosDoCompradorRow
		if err := rows.Scan(
			&i.ID,
			&i.Numero,
			&i.Status,
			&i.TotalCentavos,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pedidoPorChave = `-- name: PedidoPorChave :one
SELECT id, numero, status, total_centavos, digest_corpo
FROM pedido.pedido
WHERE comprador_id = $1 AND chave_idempotencia = $2
`

type PedidoPorChaveParams struct {
	CompradorID       pgtype.UUID
	ChaveIdempotencia pgtype.UUID
}

type PedidoPorChaveRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
	DigestCorpo   pgtype.Text
}

// O Pedido que a chave já criou, deste Comprador: a chave de outro Comprador
// não casa, porque a chave é dele (AD-11). O digest vem junto para decidir
// entre reenvio (mesmo corpo) e chave reaproveitada (corpo diferente).
func (q *Queries) PedidoPorChave(ctx context.Context, arg PedidoPorChaveParams) (PedidoPorChaveRow, error) {
	row := q.db.QueryRow(ctx, pedidoPorChave, arg.CompradorID, arg.ChaveIdempotencia)
	var i PedidoPorChaveRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.TotalCentavos,
		&i.DigestCorpo,
	)
	return i, err
}

const pedidosParaAvancar = `-- name: PedidosParaAvancar :many
SELECT p.id
FROM pedido.pedido p
WHERE p.status = ANY($1::text[])
  AND (SELECT max(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id) <= $2
ORDER BY p.id
`

type PedidosParaAvancarParams struct {
	Status []string
	Ate    pgtype.Timestamptz
}

// Os candidatos dos dois passos do tempo — a expiração da Tentativa de
// Pagamento (FR-34) e a simulação de entrega —, lidos FORA da transação: quem
// decide é a releitura travada de TravarPedido, e selecionar já travando faria
// uma transação por tique em vez de uma por Pedido. O avanço deriva do
// histórico — "está neste estado desde quando" —, nunca de estado em memória, e
// é por isso que reiniciar o contêiner retoma cada Pedido de onde parou.
//
// É a mesma conta que `pedido.ExpiraEm` mostra na tela: para um Pedido em
// AGUARDANDO_PAGAMENTO, max(ocorrido_em) É a última transição para esse Status,
// porque qualquer linha posterior o teria tirado de lá.
//
// ponytail: varredura sequencial de pedido.pedido a cada tique. O
// max(ocorrido_em) correlacionado já tem `transicao_status (pedido_id,
// ocorrido_em)`, da 5.1; quando o volume justificar, o índice que falta é
// `pedido (status, id)`, sem tocar na consulta.
func (q *Queries) PedidosParaAvancar(ctx context.Context, arg PedidosParaAvancarParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, pedidosParaAvancar, arg.Status, arg.Ate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proximoNumeroDoAno = `-- name: ProximoNumeroDoAno :one

INSERT INTO pedido.contador_numero (ano, ultimo) VALUES ($1, 1)
ON CONFLICT (ano) DO UPDATE SET ultimo = contador_numero.ultimo + 1
RETURNING ultimo
`

// As consultas do caso de uso "um Pedido nasce em AGUARDANDO_PAGAMENTO".
// Todas rodam dentro da mesma transação, passada como `tx pgx.Tx` (AD-4).
// O contador por ano resolve o número legível na própria transação: sem DDL em
// tempo de execução e sem buraco na numeração quando a transação é revertida.
// O `contador_numero` do SET é a linha em conflito — dentro do ON CONFLICT o
// nome da tabela é o apelido, e qualificá-lo pelo schema seria erro de sintaxe.
func (q *Queries) ProximoNumeroDoAno(ctx context.Context, ano int32) (int64, error) {
	row := q.db.QueryRow(ctx, proximoNumeroDoAno, ano)
	var ultimo int64
	err := row.Scan(&ultimo)
	return ultimo, err
}

const registrarTransicao = `-- name: RegistrarTransicao :exec
INSERT INTO pedido.transicao_status (pedido_id, status_anterior, status_novo, ator, motivo)
VALUES ($1, $2, $3, $4, $5)
`

type RegistrarTransicaoParams struct {
	PedidoID       pgtype.UUID
	StatusAnterior string
	StatusNovo     string
	Ator           string
	Motivo         pgtype.Text
}

// O `motivo` é anulável: nem toda transição tem um. `sqlc.narg` o deixa
// chegar como NULL, e não como texto vazio, que seria um motivo sem conteúdo.
func (q *Queries) RegistrarTransicao(ctx context.Context, arg RegistrarTransicaoParams) error {
	_, err := q.db.Exec(ctx, registrarTransicao,
		arg.PedidoID,
		arg.StatusAnterior,
		arg.StatusNovo,
		arg.Ator,
		arg.Motivo,
	)
	return err
}

const statusDoPedido = `-- name: StatusDoPedido :one
SELECT status FROM pedido.pedido WHERE id = $1
`

// A releitura do Status depois de um compare-and-swap perdido: é ela que
// separa "outro ator avançou" de "o Pedido saiu da janela de cancelamento".
// Sem trava — quem ganhou já comitou, ou o UPDATE acima teria esperado por ele.
func (q *Queries) StatusDoPedido(ctx context.Context, pedidoID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, statusDoPedido, pedidoID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const travarPedido = `-- name: TravarPedido :one
SELECT p.status,
       (SELECT max(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id)::timestamptz AS desde
FROM pedido.pedido p
WHERE p.id = $1
FOR UPDATE SKIP LOCKED
`

type TravarPedidoRow struct {
	Status string
	Desde  pgtype.Timestamptz
}

// A leitura travada da varredura. SKIP LOCKED porque o tique que encontra o
// Pedido já travado não tem o que esperar: o outro caminho está aplicando, e
// insistir só serializaria a varredura inteira num Pedido.
// O instante da última transição sai junto, e na mesma trava: a decisão de
// avançar precisa do Status e de "desde quando" travados um com o outro. Duas
// consultas travadas quase idênticas seriam duas oportunidades de divergirem.
func (q *Queries) TravarPedido(ctx context.Context, pedidoID pgtype.UUID) (TravarPedidoRow, error) {
	row := q.db.QueryRow(ctx, travarPedido, pedidoID)
	var i TravarPedidoRow
	err := row.Scan(&i.Status, &i.Desde)
	return i, err
}

const travarPedidoDoComprador = `-- name: TravarPedidoDoComprador :one
SELECT p.id, p.numero, p.status, p.total_centavos
FROM pedido.pedido p
WHERE p.id = $1 AND p.comprador_id = $2
FOR UPDATE
`

type TravarPedidoDoCompradorParams struct {
	PedidoID    pgtype.UUID
	CompradorID pgtype.UUID
}

type TravarPedidoDoCompradorRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
}

// A leitura travada do cancelamento pelo Comprador (6.3). O dono entra no
// WHERE, como em BuscarPedidoDoComprador: alheio e inexistente saem os dois
// como "nenhuma linha", o mesmo 404 (AD-11) — e o Pedido alheio nem chega a
// ser travado.
//
// FOR UPDATE que ESPERA, e não o SKIP LOCKED da varredura: o Comprador que
// cancela precisa do desfecho, e não de "tente no próximo tique". Com a linha
// presa, o Status lido é o que o compare-and-swap de Transicionar vai ver — é
// isso que faz o segundo clique ler CANCELADO (e sair sucesso sem efeito) em
// vez de perder o CAS e sair FORA_DA_JANELA_DE_CANCELAMENTO de um
// cancelamento que deu certo. É também a primeira trava do AD-4: a linha do
// Pedido antes dos Produtos, que Liberar trava depois.
func (q *Queries) TravarPedidoDoComprador(ctx context.Context, arg TravarPedidoDoCompradorParams) (TravarPedidoDoCompradorRow, error) {
	row := q.db.QueryRow(ctx, travarPedidoDoComprador, arg.PedidoID, arg.CompradorID)
	var i TravarPedidoDoCompradorRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.TotalCentavos,
	)
	return i, err
}

const travarPedidoParaAdministrador = `-- name: TravarPedidoParaAdministrador :one
SELECT p.id, p.numero, p.status, p.total_centavos
FROM pedido.pedido p
WHERE p.id = $1
FOR UPDATE
`

type TravarPedidoParaAdministradorRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
}

// A leitura travada da transição pelo Administrador (6.4). É
// TravarPedidoDoComprador sem o dono: o Administrador alcança o Pedido de
// qualquer Comprador, e a trava serve a outra coisa — prender a linha antes
// do compare-and-swap para que o Status lido seja o que o CAS vai ver.
//
// FOR UPDATE que ESPERA, e não o SKIP LOCKED da varredura: o Administrador
// clicou num botão e precisa do desfecho. É a trava que faz a corrida com a
// simulação sair como "o Pedido já está em X", e não como transição inválida.
func (q *Queries) TravarPedidoParaAdministrador(ctx context.Context, pedidoID pgtype.UUID) (TravarPedidoParaAdministradorRow, error) {
	row := q.db.QueryRow(ctx, travarPedidoParaAdministrador, pedidoID)
	var i TravarPedidoParaAdministradorRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.TotalCentavos,
	)
	return i, err
}
