// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const avancarStatus = `-- name: AvancarStatus :execrows
UPDATE pedido.pedido SET status = $1 WHERE id = $2 AND status = $3
`

type AvancarStatusParams struct {
	Para     string
	PedidoID pgtype.UUID
	De       string
}

// O único ponto de mutação do Status (AD-6), e é compare-and-swap: o estado de
// origem entra no WHERE, e zero linhas afetadas significa "o estado já
// avançou", nunca "o Pedido não existe" — as duas coisas são o mesmo desfecho
// esperado para quem chama.
func (q *Queries) AvancarStatus(ctx context.Context, arg AvancarStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, avancarStatus, arg.Para, arg.PedidoID, arg.De)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const buscarPedidoDoComprador = `-- name: BuscarPedidoDoComprador :one
SELECT p.id, p.numero, p.status, p.total_centavos,
       -- O cast é carga: sem ele o sqlc não infere o tipo da subconsulta e
       -- devolve ` + "`" + `interface{}` + "`" + `, que só falharia no Scan em tempo de execução.
       (SELECT max(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id)::timestamptz AS atualizado_em
FROM pedido.pedido p
WHERE p.id = $1 AND p.comprador_id = $2
`

type BuscarPedidoDoCompradorParams struct {
	PedidoID    pgtype.UUID
	CompradorID pgtype.UUID
}

type BuscarPedidoDoCompradorRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
	AtualizadoEm  pgtype.Timestamptz
}

// A leitura da tela de acompanhamento. O dono entra no WHERE, e não numa
// checagem depois: Pedido de outro Comprador e Pedido inexistente saem os dois
// como "nenhuma linha", que é o mesmo 404 — não vaza existência.
// O instante é o da última transição, absoluto e vindo do servidor: o
// navegador nunca conta duração.
func (q *Queries) BuscarPedidoDoComprador(ctx context.Context, arg BuscarPedidoDoCompradorParams) (BuscarPedidoDoCompradorRow, error) {
	row := q.db.QueryRow(ctx, buscarPedidoDoComprador, arg.PedidoID, arg.CompradorID)
	var i BuscarPedidoDoCompradorRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.TotalCentavos,
		&i.AtualizadoEm,
	)
	return i, err
}

const criarItemPedido = `-- name: CriarItemPedido :exec
INSERT INTO pedido.item_pedido
    (pedido_id, produto_id, nome, vendedor_nome, preco_praticado_centavos, quantidade)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CriarItemPedidoParams struct {
	PedidoID               pgtype.UUID
	ProdutoID              pgtype.UUID
	Nome                   string
	VendedorNome           string
	PrecoPraticadoCentavos int64
	Quantidade             int32
}

// O Item congela o que era verdade no instante da compra: nome, preço
// praticado e Vendedor são cópia, e não referência.
func (q *Queries) CriarItemPedido(ctx context.Context, arg CriarItemPedidoParams) error {
	_, err := q.db.Exec(ctx, criarItemPedido,
		arg.PedidoID,
		arg.ProdutoID,
		arg.Nome,
		arg.VendedorNome,
		arg.PrecoPraticadoCentavos,
		arg.Quantidade,
	)
	return err
}

const criarPedido = `-- name: CriarPedido :one
INSERT INTO pedido.pedido (numero, comprador_id, status, total_centavos)
VALUES ($1, $2, $3, $4)
RETURNING id, numero, status, total_centavos
`

type CriarPedidoParams struct {
	Numero        string
	CompradorID   pgtype.UUID
	Status        string
	TotalCentavos int64
}

type CriarPedidoRow struct {
	ID            pgtype.UUID
	Numero        string
	Status        string
	TotalCentavos int64
}

func (q *Queries) CriarPedido(ctx context.Context, arg CriarPedidoParams) (CriarPedidoRow, error) {
	row := q.db.QueryRow(ctx, criarPedido,
		arg.Numero,
		arg.CompradorID,
		arg.Status,
		arg.TotalCentavos,
	)
	var i CriarPedidoRow
	err := row.Scan(
		&i.ID,
		&i.Numero,
		&i.Status,
		&i.TotalCentavos,
	)
	return i, err
}

const pedidosParaAvancar = `-- name: PedidosParaAvancar :many
SELECT p.id
FROM pedido.pedido p
WHERE p.status = ANY($1::text[])
  AND (SELECT max(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id) <= $2
ORDER BY p.id
`

type PedidosParaAvancarParams struct {
	Status []string
	Ate    pgtype.Timestamptz
}

// Os candidatos da simulação de entrega, lidos FORA da transação: quem decide
// é a releitura travada de TravarPedido, e selecionar já travando faria uma
// transação por tique em vez de uma por Pedido. O avanço deriva do histórico —
// "está neste estado desde quando" —, nunca de estado em memória, e é por isso
// que reiniciar o contêiner retoma cada Pedido de onde parou.
//
// ponytail: varredura sequencial de pedido.pedido a cada tique, com um
// max(ocorrido_em) correlacionado por linha — a tabela só tem
// pedido_comprador_id_idx, e esta épica proíbe migração nova. Na demonstração
// são dezenas de Pedidos e não se mede. Quando o volume justificar, os índices
// que a levantam são `pedido (status, id)` e
// `transicao_status (pedido_id, ocorrido_em DESC)`, sem tocar na consulta.
func (q *Queries) PedidosParaAvancar(ctx context.Context, arg PedidosParaAvancarParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, pedidosParaAvancar, arg.Status, arg.Ate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const proximoNumeroDoAno = `-- name: ProximoNumeroDoAno :one

INSERT INTO pedido.contador_numero (ano, ultimo) VALUES ($1, 1)
ON CONFLICT (ano) DO UPDATE SET ultimo = contador_numero.ultimo + 1
RETURNING ultimo
`

// As consultas do caso de uso "um Pedido nasce em AGUARDANDO_PAGAMENTO".
// Todas rodam dentro da mesma transação, passada como `tx pgx.Tx` (AD-4).
// O contador por ano resolve o número legível na própria transação: sem DDL em
// tempo de execução e sem buraco na numeração quando a transação é revertida.
// O `contador_numero` do SET é a linha em conflito — dentro do ON CONFLICT o
// nome da tabela é o apelido, e qualificá-lo pelo schema seria erro de sintaxe.
func (q *Queries) ProximoNumeroDoAno(ctx context.Context, ano int32) (int64, error) {
	row := q.db.QueryRow(ctx, proximoNumeroDoAno, ano)
	var ultimo int64
	err := row.Scan(&ultimo)
	return ultimo, err
}

const registrarTransicao = `-- name: RegistrarTransicao :exec
INSERT INTO pedido.transicao_status (pedido_id, status_anterior, status_novo, autor)
VALUES ($1, $2, $3, $4)
`

type RegistrarTransicaoParams struct {
	PedidoID       pgtype.UUID
	StatusAnterior string
	StatusNovo     string
	Autor          string
}

func (q *Queries) RegistrarTransicao(ctx context.Context, arg RegistrarTransicaoParams) error {
	_, err := q.db.Exec(ctx, registrarTransicao,
		arg.PedidoID,
		arg.StatusAnterior,
		arg.StatusNovo,
		arg.Autor,
	)
	return err
}

const travarPedido = `-- name: TravarPedido :one
SELECT p.status,
       (SELECT max(t.ocorrido_em) FROM pedido.transicao_status t WHERE t.pedido_id = p.id)::timestamptz AS desde
FROM pedido.pedido p
WHERE p.id = $1
FOR UPDATE SKIP LOCKED
`

type TravarPedidoRow struct {
	Status string
	Desde  pgtype.Timestamptz
}

// A leitura travada da varredura. SKIP LOCKED porque o tique que encontra o
// Pedido já travado não tem o que esperar: o outro caminho está aplicando, e
// insistir só serializaria a varredura inteira num Pedido.
// O instante da última transição sai junto, e na mesma trava: a decisão de
// avançar precisa do Status e de "desde quando" travados um com o outro. Duas
// consultas travadas quase idênticas seriam duas oportunidades de divergirem.
func (q *Queries) TravarPedido(ctx context.Context, pedidoID pgtype.UUID) (TravarPedidoRow, error) {
	row := q.db.QueryRow(ctx, travarPedido, pedidoID)
	var i TravarPedidoRow
	err := row.Scan(&i.Status, &i.Desde)
	return i, err
}
