// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gerado

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PedidoContadorNumero struct {
	Ano    int32
	Ultimo int64
}

type PedidoItemPedido struct {
	ID                     pgtype.UUID
	PedidoID               pgtype.UUID
	ProdutoID              pgtype.UUID
	Nome                   string
	VendedorNome           string
	PrecoPraticadoCentavos int64
	Quantidade             int32
}

type PedidoPedido struct {
	ID            pgtype.UUID
	Numero        string
	CompradorID   pgtype.UUID
	Status        string
	TotalCentavos int64
}

type PedidoTransicaoStatus struct {
	ID             pgtype.UUID
	PedidoID       pgtype.UUID
	StatusAnterior string
	StatusNovo     string
	Autor          string
	OcorridoEm     pgtype.Timestamptz
}
