// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package gerado

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PedidoContadorNumero struct {
	Ano    int32
	Ultimo int64
}

type PedidoFaixaFrete struct {
	ID            pgtype.UUID
	CepInicio     pgtype.Text
	CepFim        pgtype.Text
	Regiao        string
	ValorCentavos int64
	Padrao        bool
}

type PedidoItemPedido struct {
	ID                     pgtype.UUID
	PedidoID               pgtype.UUID
	ProdutoID              pgtype.UUID
	Nome                   string
	VendedorNome           string
	PrecoPraticadoCentavos int64
	Quantidade             int32
}

type PedidoPedido struct {
	ID                   pgtype.UUID
	Numero               string
	CompradorID          pgtype.UUID
	Status               string
	TotalCentavos        int64
	SubtotalCentavos     int64
	FreteCentavos        int64
	EnderecoDestinatario pgtype.Text
	EnderecoCep          pgtype.Text
	EnderecoLogradouro   pgtype.Text
	EnderecoNumero       pgtype.Text
	EnderecoComplemento  pgtype.Text
	EnderecoBairro       pgtype.Text
	EnderecoCidade       pgtype.Text
	EnderecoUf           pgtype.Text
	ChaveIdempotencia    pgtype.UUID
	DigestCorpo          pgtype.Text
}

type PedidoTransicaoStatus struct {
	ID             pgtype.UUID
	PedidoID       pgtype.UUID
	StatusAnterior string
	StatusNovo     string
	Ator           string
	OcorridoEm     pgtype.Timestamptz
	Motivo         pgtype.Text
}
