// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consultas.sql

package gerado

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contarVisiveis = `-- name: ContarVisiveis :one
SELECT count(*) FROM catalogo.produto_visivel
`

func (q *Queries) ContarVisiveis(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, contarVisiveis)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listarVisiveis = `-- name: ListarVisiveis :many

SELECT id, nome, preco_centavos, imagem_url, estoque_disponivel
FROM catalogo.produto_visivel
ORDER BY id
LIMIT $2 OFFSET $1
`

type ListarVisiveisParams struct {
	Deslocamento int32
	Limite       int32
}

type ListarVisiveisRow struct {
	ID                pgtype.UUID
	Nome              string
	PrecoCentavos     int64
	ImagemUrl         string
	EstoqueDisponivel int32
}

// `busca` não tem tabelas: lê o Catálogo só pela VIEW produto_visivel (AD-2,
// AD-16), que já aplica o predicado de visibilidade (AD-19). Nenhum `WHERE
// ativo` aqui. O desempate final é sempre `id` (AD-18); a ordenação da 3.9
// antepõe a sua chave.
func (q *Queries) ListarVisiveis(ctx context.Context, arg ListarVisiveisParams) ([]ListarVisiveisRow, error) {
	rows, err := q.db.Query(ctx, listarVisiveis, arg.Deslocamento, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarVisiveisRow
	for rows.Next() {
		var i ListarVisiveisRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.PrecoCentavos,
			&i.ImagemUrl,
			&i.EstoqueDisponivel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
